### PR TITLE
fix: error on embeddings; not currently implemented

### LINKED ISSUE #9739: gemma3 embeddings support
### What is the issue?

gemma3:1b fails to generate embeddings, other models work.

```sh-session
$ curl http://localhost:11434/api/embed -d '{
                                    "model": "gemma3:1b",
                                    "input": "Llamas are members of the camelid family"
                                  }'
{"model":"gemma3:1b","embeddings":[null],"total_duration":795587042,"load_duration":644392083,"prompt_eval_count":10}⏎
```

### Relevant log output

```shell
time=2025-03-13T13:49:34.664-04:00 level=INFO source=server.go:624 msg="llama runner started in 0.50 seconds"
time=2025-03-13T13:49:34.846-04:00 level=WARN source=runner.go:429 msg="generation of embedding outputs not yet supported"
[GIN] 2025/03/13 - 13:49:34 | 200 |  818.674917ms |       127.0.0.1 | POST     "/api/embed"
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.6.0

### PR DESCRIPTION
**Pull request by mxyng**
embeddings is not (currently) supported in the ollama engine so error on requests to `/api/embed` for any models that are routed to that engine

without this change, embeddings on the ollama engine will return an empty list rather than error which hides the non-support

resolves #9739

### CODE REVIEW

File: runner/ollamarunner/runner.go [hunk 1]
```diff
@@ -927,9 +927,14 @@ func Execute(args []string) error {
 	defer listener.Close()
 
 	mux := http.NewServeMux()
-	mux.HandleFunc("/embedding", server.embeddings)
-	mux.HandleFunc("/completion", server.completion)
-	mux.HandleFunc("/health", server.health)
+	// TODO: support embeddings
+	// mux.HandleFunc("/embedding", server.embeddings)
+	mux.HandleFunc("POST /embedding", func(w http.ResponseWriter, r *http.Request) {
+		http.Error(w, "embeddings currently not implemented", http.StatusNotImplemented)
```
Comment (jmorganca) [inline runner/ollamarunner/runner.go:933]:
```suggestion
		http.Error(w, "this model does not support embeddings", http.StatusNotImplemented)
```

Comment (jmorganca) [reply runner/ollamarunner/runner.go:933]: This error message will hold until we support an embedding model this runner 😊

**Review by jmorganca — APPROVED** [review]
