### PR TITLE
Fix GetModelInfo

### LINKED ISSUE #11395: Ollama jumps to the CLI and throws an error message after requesting parameters
### What is the issue?

When i try to use devstral for coding and increase the context window apparently has been accepted the change,  but after veryfing with **/show parameters**   then exits the cli and shows an error message

### Relevant log output

```shell
~  ollama run devstral:latest                                                                                                                     ✔  ubuntu@ccvassh100 
>>> /show parameters
No parameters were specified for this model.
>>> /set parameter num_ctx 32768
Set parameter 'num_ctx' to '32768'
>>> /set parameter num_ctx 32768
Set parameter 'num_ctx' to '32768'
>>> /show parameters
error: couldn't get model
Error: something went wrong, please see the ollama server logs for details
 ~  journalctl -f                                                                                                                          1 ✘  23s  ubuntu@ccvassh100 
Jul 12 09:14:23 ccvassh100 ollama[497197]: github.com/gin-gonic/gin@v1.10.0/logger.go:249 (0x63c33a9cf5eb)
Jul 12 09:14:23 ccvassh100 ollama[497197]: github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x63c33a9cea11)
Jul 12 09:14:23 ccvassh100 ollama[497197]: github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x63c33a9ce4a0)
Jul 12 09:14:23 ccvassh100 ollama[497197]: github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x63c33a9cdfc9)
Jul 12 09:14:23 ccvassh100 ollama[497197]: net/http/server.go:2822 (0x63c33a60ba43)
Jul 12 09:14:23 ccvassh100 ollama[497197]: net/http/server.go:3301 (0x63c33a6294cd)
Jul 12 09:14:23 ccvassh100 ollama[497197]: net/http/server.go:2102 (0x63c33a608044)
Jul 12 09:14:23 ccvassh100 ollama[497197]: runtime/asm_amd64.s:1700 (0x63c33a313480)
Jul 12 09:14:23 ccvassh100 ollama[497197]: 
Jul 12 09:14:23 ccvassh100 ollama[497197]: [GIN] 2025/07/12 - 09:14:23 | 500 |   49.789397ms |       127.0.0.1 | POST     "/api/show"
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.9.6

### PR DESCRIPTION
**Pull request by pdevine**
This change carries #11396 and fixes #11395.

If GetModelInfo was called with optional params it was throwing an error if the model didn't have any parameters already defined for it.

### CODE REVIEW

File: server/routes.go [hunk 1]
```diff
@@ -844,6 +844,9 @@ func GetModelInfo(req api.ShowRequest) (*api.ShowResponse, error) {
 
 	for k, v := range req.Options {
 		if _, ok := req.Options[k]; ok {
+			if m.Options == nil {
+				m.Options = make(map[string]any)
+			}
 			m.Options[k] = v
 		}
 	}
```
Comment (BruceMacD) [inline server/routes.go]: This options building code looks kinda awkward, I think this would be simpler:

```suggestion
if len(req.Options) > 0 {
    if m.Options == nil {
        m.Options = make(map[string]any)
    }
    for k, v := range req.Options {
        m.Options[k] = v
    }
}
```

I dont see a reason for the `ok` assertion and checking m.Options being nil on each iteration

**Review by BruceMacD — APPROVED** [review]
