### PR TITLE
Switch back to subprocessing for llama.cpp

### LINKED ISSUE #1691: loading many models 1 after another corrupts ollama
I feel this is a major bug, as anyone using ollama for an extended time using several models will have the same issue.

I'm using https://github.com/iplayfast/OllamaPlayground/tree/main/createnotes#readme which tests all the models on your system. It initially loads each model and says hello just to test. This is where the problem lies.

ollama serve
Error: listen tcp 127.0.0.1:11434: bind: address already in use

These are my models:
```
 ollama list
NAME                           	ID          	SIZE  	MODIFIED     
chris/mr_t:latest              	e792712b8728	3.8 GB	9 hours ago 	
DrunkSally:latest              	7b378c3757fc	3.8 GB	7 days ago  	
Guido:latest                   	158599e734fb	26 GB 	7 days ago  	
Jim:latest                     	2c7476fb37de	3.8 GB	6 weeks ago 	
Mario:latest                   	902e3a8e5ed7	3.8 GB	6 weeks ago 	
MrT:latest                     	e792712b8728	3.8 GB	8 days ago  	
Polly:latest                   	19982222ada1	4.1 GB	5 weeks ago 	
Sally:latest                   	903b51bbe623	3.8 GB	10 days ago 	
Ted:latest                     	fdabf1286f32	4.1 GB	7 days ago  	
alfred:latest                  	e46325710c52	23 GB 	4 weeks ago 	
bakllava:latest                	3dd68bd4447c	4.7 GB	4 days ago  	
codebooga:latest               	05b83c5673dc	19 GB 	5 weeks ago 	
codellama:latest               	8fdf8f752f6e	3.8 GB	3 weeks ago 	
codeup:latest                  	54289661f7a9	7.4 GB	6 weeks ago 	
deepseek-coder:33b             	2941d6ab92f3	18 GB 	4 weeks ago 	
deepseek-coder:latest          	140a485970a6	776 MB	2 weeks ago 	
deepseek-llm:latest            	9aab369a853b	4.0 GB	9 days ago  	
dolphin-mixtral:latest         	4b33b01bf336	26 GB 	8 days ago  	
everythinglm:latest            	bf6610a21b1e	7.4 GB	6 weeks ago 	
falcon:latest                  	4280f7257e73	4.2 GB	11 hours ago	
llama2:latest                  	fe938a131f40	3.8 GB	6 weeks ago 	
llama2-uncensored:latest       	44040b922233	3.8 GB	4 weeks ago 	
llava:latest                   	e4c3eb471fd8	4.5 GB	9 days ago  	
magicoder:latest               	8007de06f5d9	3.8 GB	2 weeks ago 	
medllama2:latest               	a53737ec0c72	3.8 GB	6 weeks ago 	
mistral:7b                     	d364aa8d131e	4.1 GB	6 weeks ago 	
mistral:instruct               	8aa307f73b26	4.1 GB	2 months ago	
mistral:latest                 	8aa307f73b26	4.1 GB	2 months ago	
mistral:text                   	3e3d0b9dcb6a	4.1 GB	6 weeks ago 	
mistrallite:latest             	5393d4f5f262	4.1 GB	6 weeks ago 	
mixtralcpu:latest              	8fca5114ed19	26 GB 	9 hours ago 	
neural-chat:latest             	f4c6a8e532e8	4.1 GB	2 weeks ago 	
nexusraven:latest              	336957c1d527	7.4 GB	6 weeks ago 	
openhermes2.5-mistral:latest   	ca4cd4e8a562	4.1 GB	5 weeks ago 	
orca2:13b                      	a8dcfac3ac32	7.4 GB	4 weeks ago 	
orca2:latest                   	ea98cc422de3	3.8 GB	2 weeks ago 	
phi:latest                     	e22226989b6c	1.6 GB	3 days ago  	
phind-codellama:latest         	64cce35068a2	19 GB 	5 weeks ago 	
samantha-mistral:latest        	f7c8c9be1da0	4.1 GB	6 weeks ago 	
solar:latest                   	059fdabbe6e6	6.1 GB	5 days ago  	
sqlcoder:latest                	77ac14348387	4.1 GB	6 weeks ago 	
stablelm-zephyr:latest         	7c596e78b1fc	1.6 GB	2 weeks ago 	
starling-lm:latest             	0eab7e16513a	4.1 GB	3 weeks ago 	
uncensored:latest              	8fb4f61e2281	8.9 GB	2 days ago  	
wizard-math:latest             	5ab8dc2115d3	4.1 GB	9 hours ago 	
wizard-vicuna-uncensored:7b    	72fc3c2b99dc	3.8 GB	10 days ago 	
wizard-vicuna-uncensored:latest	72fc3c2b99dc	3.8 GB	5 weeks ago 	
wizardlm-uncensored:latest     	886a369d74fc	7.4 GB	13 days ago 	
xwinlm:latest                  	0fa68068d970	3.8 GB	6 weeks ago 	
yarn-mistral:latest            	8e9c368a0ae4	4.1 GB	9 days ago  	
yi:latest                      	59e2d70c6939	3.5 GB	10 days ago 	
zephyr:latest                  	1629f2a8a495	4.1 GB	6 weeks ago 	
```

This is the output after loading them one after another:
```
python CreateNotes.py 
Attempting to load each model to see if they can be loaded
   attempting to load model chris/mr_t:latest
         model chris/mr_t:latest loaded in 4.0 seconds
   attempting to load model DrunkSally:latest
         model DrunkSally:latest loaded in 8.7 seconds
   attempting to load model Guido:latest
         model Guido:latest loaded in 33.1 seconds
   attempting to load model Jim:latest
         model Jim:latest loaded in 4.0 seconds
   attempting to load model Mario:latest
         model Mario:latest loaded in 1.2 seconds
   attempting to load model MrT:latest
         model MrT:latest loaded in 0.7 seconds
   attempting to load model Polly:latest
         model Polly:latest loaded in 37.9 seconds
   attempting to load model Sally:latest
         model Sally:latest loaded in 2.1 seconds
   attempting to load model Ted:latest
         model Ted:latest loaded in 1.7 seconds
   attempting to load model alfred:latest
         model alfred:latest loaded in 155.2 seconds
   attempting to load model bakllava:latest
         model bakllava:latest loaded in 32.8 seconds
   attempting to load model codebooga:latest
         model codebooga:latest loaded in 110.1 seconds
   attempting to load model codellama:latest
         model codellama:latest loaded in 24.7 seconds
   attempting to load model codeup:latest
         model codeup:latest loaded in 52.7 seconds
   attempting to load model deepseek-coder:33b
         model deepseek-coder:33b loaded in 107.6 seconds
   attempting to load model deepseek-coder:latest
         model deepseek-coder:latest loaded in 7.0 seconds
   attempting to load model deepseek-llm:latest
         model deepseek-llm:latest loaded in 14.4 seconds
   attempting to load model dolphin-mixtral:latest
         model dolphin-mixtral:latest loaded in 93.7 seconds
   attempting to load model everythinglm:latest
         model everythinglm:latest loaded in 48.2 seconds
   attempting to load model falcon:latest
         model falcon:latest loaded in 34.2 seconds
   attempting to load model llama2:latest
         model llama2:latest loaded in 5.9 seconds
   attempting to load model llama2-uncensored:latest
         model llama2-uncensored:latest loaded in 1.8 seconds
   attempting to load model llava:latest
         model llava:latest loaded in 6.2 seconds
   attempting to load model magicoder:latest
         model magicoder:latest loaded in 3.7 seconds
   attempting to load model medllama2:latest
         model medllama2:latest loaded in 22.5 seconds
   attempting to load model mistral:7b
         model mistral:7b loaded in 26.0 seconds
   attempting to load model mistral:instruct
         model mistral:instruct loaded in 0.1 seconds
   attempting to load model mistral:latest
         model mistral:latest loaded in 0.1 seconds
   attempting to load model mistral:text
         model mistral:text loaded in 36.3 seconds
   attempting to load model mistrallite:latest
         model mistrallite:latest loaded in 38.2 seconds
   attempting to load model mixtralcpu:latest
Error: Ollama call failed with status code 500. Details: timed out waiting for llama runner to start
         model mixtralcpu:latest ------------not loaded------------ in 182.2 seconds
   attempting to load model nexusraven:latest
         model nexusraven:latest loaded in 60.8 seconds
   attempting to load model openhermes2.5-mistral:latest
         model openhermes2.5-mistral:latest loaded in 25.0 seconds
   attempting to load model orca2:13b
         model orca2:13b loaded in 46.4 seconds
   attempting to load model orca2:latest
         model orca2:latest loaded in 25.7 seconds
   attempting to load model phi:latest
         model phi:latest loaded in 17.9 seconds
   attempting to load model phind-codellama:latest
         model phind-codellama:latest loaded in 123.8 seconds
   attempting to load model samantha-mistral:latest
         model samantha-mistral:latest loaded in 33.1 seconds
   attempting to load model solar:latest
         model solar:latest loaded in 42.2 seconds
   attempting to load model sqlcoder:latest
Timed out after 300 seconds for question: are you there
```
sqlcoder isn't a big model. I had originally thought meditron was the problem so I removed it. and it just went to the next one.
mixtralcpu is from https://ollama.ai/chris/mixtralcpu which uses loads into memory instead of the gpu. (It loaded from command line fine).

### LINKED ISSUE #1848: Ollama v0.1.18+ does not fully unload from GPU when idle
**OS:** Ubuntu 22.04
**Environment:** Docker/nvidia container
**Server:** Dell Poweredge R720
**GPUs:** Nvidia Tesla P40 24GB
**GPU quantity:** 2
**Model:** any (ie.  dolphin-mixtral:8x7b-v2.5-q6_K)

```
 docker pull ollama/ollama:0.1.17
 docker run -d --gpus=all -v ~/ollama:/root/.ollama -p 11434:11434 --name ollama17 ollama/ollama:0.1.17
 docker exec -it ollama17 ollama run dolphin-mixtral:8x7b-v2.5-q6_K
```

Previous observation on Ollama v0.1.17. When model is loaded VRAM utilization is visible via nvidia-smi a pair of processes are also visible:
`...p/gguf/build/cuda/bin/ollama-runner`
Each process uses 50-150w per GPU while running inference, 50-52w idle but model still loaded. 

ollama-0 1 17_modelloaded

After a period of idle time, the model is **unloaded**. Both GPUs drop to 10-12w a piece with no visible process running

ollama-0 1 17_modelunloaded

```
 docker pull ollama/ollama:0.1.18
 docker run -d --gpus=all -v ~/ollama:/root/.ollama -p 11434:11434 --name ollama18 ollama/ollama:0.1.18
 docker exec -it ollama18 ollama run dolphin-mixtral:8x7b-v2.5-q6_K
```

Observation on Ollama v0.1.18. When model is loaded VRAM utilization is visible via nvidia-smi a pair of processes are also visible, but under a different path:
`/bin/ollama`
Each process uses 50-150w per GPU while running inference, 50-52w idle but model still loaded. 

ollama-0 1 18_modelloaded

After a period of idle time, the model is **unloaded**, _but process is still running_. **Both GPUs pull equivalent wattage as idle/model loaded.**

ollama-0 1 18_modelunloaded

The server is powered on 24/7 and tuned to pull 120w w/o GPUs. Ollama is idle 95% of time. Prior, P40s were adding a combined 24w additional power draw idle under v0.1.17. Now with v0.1.18, the P40s adding a combined 110w additional power draw. 86w difference.

Does /bin/ollama need to be running the entire time?

### LINKED ISSUE #1871: Switching from a high `num_ctx` to a model with a low `num_ctx` causes cuda out of memory errors
When switching from a large context window to a small one (a high `num_ctx` to a low `num_ctx`), Ollama will error due to out of memory. It seems that it will incorrectly try to re-allocate the same amount of memory as before (vs a new, smaller amount).

### LINKED ISSUE #2767: Fully unload GPU memory on NVIDIA non-VMM GPUs when idle
The fix for #1848 works for VMM GPUs, but still leaves remaining memory allocations for non-VMM GPUs.

### PR DESCRIPTION
**Pull request by dhiltgen**
This should resolve a number of memory leak and stability defects by allowing us to isolate llama.cpp in a separate process and shutdown when idle, and gracefully restart if it has problems.  This also serves as a first step to be able to run multiple copies to support multiple models concurrently.

Tested on Windows, Linux, Mac.  Nvidia/AMD, and simulated a number of different failure modes to ensure it detected the runner not responding and restarted it on next request.

Fixes #1691 
Fixes #1848 
Fixes #1871
Fixes #2767

### CODE REVIEW

File: llm/server.go [hunk 1]
```diff
@@ -0,0 +1,807 @@
...
+		select {
+		case err := <-s.done:
+			return fmt.Errorf("llama runner process has terminated: %v", err)
+		case <-ticker.C:
+			if time.Now().After(expiresAt) {
+				// timeout
+				return fmt.Errorf("timed out waiting for llama runner to start")
+			}
+			if s.cmd.ProcessState != nil {
+				return fmt.Errorf("llama runner process no longer running: %d", s.cmd.ProcessState.ExitCode())
```
Comment (BruceMacD) [inline llm/server.go:379]: This error will likely be returned for many different "root" errors, which will cause many people to end up in issues not related to their actual problems.

You can see in a previous implementation that I redirected the stderr to a function that intercepts the log messages to track the actual error. If possible I'd like to do something similar again.
https://github.com/ollama/ollama/blob/5e7fd6906f4653fa671aa5d2e2d4dd5bdf17fd36/llm/llama.go#L430

File: llm/server.go [hunk 2]
```diff
@@ -0,0 +1,807 @@
...
+		params = append(params, "--numa")
+	}
+
+	// Loop through potential servers
+	var finalErr error
+	for i := 0; i < len(servers); i++ {
+		dir := available[servers[i]]
+
+		// Find an available port, retry on each iterration in case the failure was a port conflict race
+		port := 0
```
[the remark this answers is not in the document]
Comment (dhiltgen) [reply llm/server.go:226]: The kernel picks a random high number port that's available (it's not sequential), so I think the probability of some other app starting in this time window is exceedingly small.  I'm inclined to not add the complexity of port conflict detection.

File: llm/server.go (hunk 1 above)
Comment (dhiltgen) [reply llm/server.go:379]: Thanks! I'll port this code over.

Comment (dhiltgen) [reply llm/server.go]: With the current setup, this is going to have somewhat limited value.  With the current structure, the common scenario is some failure in the GPU runner, and the retry logic means we'll switch to the CPU runner(s) and the captured last error will only be reported in the log.  If there's a problem with the model, then we'd iterate through, all the runners would fail, and we would bubble that back up through the API.

In the future it may be interesting to explore warnings bubbling up in the API so that we could capture this fallback scenario and report why we couldn't load on the GPU but are running on CPU.

File: llm/payload.go [hunk 3]
```diff
@@ -0,0 +1,223 @@
...
+	payloadsDir, err := gpu.PayloadsDir()
+	if err != nil {
+		return err
+	}
+
+	slog.Info("extracting embedded files", "dir", payloadsDir)
+
+	// also extract the .metal shader on darwin/arm64
+	if runtime.GOOS == "darwin" && runtime.GOARCH == "arm64" {
+		err := extractFiles(payloadsDir, "build/*/*/*/bin/ggml-metal.metal.gz")
```
Comment (BruceMacD) [inline llm/payload.go:33]: TODO: we will need to test this on an Intel Mac

File: server/routes.go [hunk 4]
```diff
@@ -286,9 +292,8 @@ func GenerateHandler(c *gin.Context) {
 	go func() {
 		defer close(ch)
 
-		fn := func(r llm.PredictResult) {
+		fn := func(r llm.CompletionResponse) {
 			// Update model expiration
-			loaded.expireAt = time.Now().Add(sessionDuration)
```
Comment (BruceMacD) [inline server/routes.go:291]: good catch

**Review by BruceMacD — COMMENTED** [review]
This is looking good to me code wise, just need to test it a lot and seems shippable

File: llm/server.go [hunk 5]
```diff
@@ -0,0 +1,829 @@
...
+		slog.Debug("server unhealthy", "error", err)
+		return err
+	}
+	return nil
+}
+
+func (s *LlamaServer) waitUntilRunning() error {
+	start := time.Now()
+	expiresAt := time.Now().Add(3 * time.Minute) // be generous with timeout, large models can take a while to load
+	ticker := time.NewTicker(200 * time.Millisecond)
```
Comment (jmorganca) [inline llm/server.go:374]: Should we lower this? I imagine an http request to loopback will take no longer than a few ms. Thinking of worst case scenario where the model is loaded and we wait another 100ms to begin inference.

Comment (jmorganca) [reply llm/server.go:374]: Perhaps a good value is 50ms or at max 100ms?

File: llm/payload.go [hunk 6]
```diff
@@ -0,0 +1,223 @@
...
+func Init() error {
+	payloadsDir, err := gpu.PayloadsDir()
+	if err != nil {
+		return err
+	}
+
+	slog.Info("extracting embedded files", "dir", payloadsDir)
+
+	// also extract the .metal shader on darwin/arm64
+	if runtime.GOOS == "darwin" && runtime.GOARCH == "arm64" {
```
Comment (jmorganca) [inline llm/payload.go:32]: Do we still need this? We can compile the .metal file in with `LLAMA_METAL_EMBED_LIBRARY`

File: llm/payload.go [hunk 7]
```diff
@@ -0,0 +1,223 @@
...
+	slog.Info(fmt.Sprintf("Dynamic LLM libraries %v", variants))
+	slog.Debug("Override detection logic by setting OLLAMA_LLM_LIBRARY")
+
+	return nil
+}
+
+// binary names may contain an optional variant separated by '_'
+// For example, "ollama_rocm_v6" and "ollama_rocm_v5" or "ollama_cpu" and "ollama_cpu_avx2"
+// Any library without a variant is the lowest common denominator
+func available() map[string]string {
```
Comment (jmorganca) [inline llm/payload.go:62]: A better name here might be `librariesAvailable` (sorry, this was my doing)

File: llm/server.go [hunk 8]
```diff
@@ -0,0 +1,829 @@
...
+					})
+					return nil
+				}
+			}
+		}
+
+		if err := scanner.Err(); err != nil {
+			if strings.Contains(err.Error(), "unexpected EOF") {
+				s.Close()
+				return fmt.Errorf("llama runner exited, you may not have enough available memory to run this model")
```
Comment (jmorganca) [inline llm/server.go:643]: We might want to edit this to be more generic (e.g. force killing a subprocess will cause it)

```suggestion
				return fmt.Errorf("an unknown error was encountered while running the model")
```

**Review by jmorganca — APPROVED** [review]
This is overall looking great! LGTM once integration tests pass and we test it on all platform variants

**Review by BruceMacD — APPROVED** [review]

**Comment by dhiltgen** [comment]
@oldmanjk this PR switches the GPU specific code over to a subprocess, which will unload after expiration of the keep alive timeout as long as requests are not being sent.   If you start the server and don't make any requests, no GPU resources should be used.  Once you send a request, then we'll start using GPU resources.  

If that's not the behavior you're seeing, can you explain your test setup a bit more where you see it holding VRAM indefinitely in an idle setup?

**Comment by dhiltgen** [comment]
Ah, this is a unintended side effect after I rebased on top of #2279 which was recently merged.    Thanks for catching this @oldmanjk!

It looks like our new cudart based GPU discovery isn't unloading when idle.  The brunt of the VRAM is cleared with the subprocess, but the main process still holds ~30M

At Startup:
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    198339      C   ./ollama-linux-amd64               29MiB |
+-----------------------------------------------------------------------------+
```

After loading a small model
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    198339      C   ./ollama-linux-amd64               29MiB |
|    0   N/A  N/A    198507      C   ...a_v11/ollama_llama_server     2783MiB |
+-----------------------------------------------------------------------------+
```

After it unloads the subprocess once idle
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    198339      C   ./ollama-linux-amd64               29MiB |
+-----------------------------------------------------------------------------+
```

I'll figure out how to get it unloaded between queries and update the PR.

**Comment by dhiltgen** [comment]
GPU memory leak fixed and confirmed on linux and windows.

**Review by jmorganca — APPROVED** [review]
