### PR TITLE
Fix use_mmap for modefiles

### LINKED ISSUE #5198: use_mmap: Error: invalid int value [false]
### What is the issue?

When adding the `use_mmap` parameter to a modelfile, it used to be like this: `PARAMETER use_mmap false`. Since 0.1.45, this does not work, it wants an integer value. So I put `PARAMETER use_mmap 0`. This allows me to create the modelfile.

However, when attempting to run the model, it comes back with this error: `Error: option "use_mmap" must be of type boolean`

Seems like a cast was forgotten somewhere maybe?

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.45

### PR DESCRIPTION
**Pull request by dhiltgen**
PR #5205 was incomplete and missed handling numeric json values.  This switches to a pointer type to represent undefined as nil.

Fixes #5198

```
% cat use_mmap.modelfile
FROM library/llama2
PARAMETER use_mmap false
% ollama create test -f ./use_mmap.modelfile
transferring model data
using existing layer sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
...
writing manifest
success
% ollama run test
>>> Send a message (/? for help)
% grep "starting llama server" server.log
time=2024-06-23T12:59:32.057-07:00 level=INFO source=server.go:363 msg="starting llama server" cmd="/tmp/ollama4152649118/runners/cpu_avx2/ollama_llama_server --model /home/daniel/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 --ctx-size 2048 --batch-size 512 --embedding --log-disable --no-mmap --parallel 1 --port 34091"
```

### CODE REVIEW

File: api/types.go [hunk 1]
```diff
@@ -648,6 +602,17 @@ func FormatParams(params map[string][]string) (map[string]interface{}, error) {
 				case reflect.Slice:
 					// TODO: only string slices are supported right now
 					out[key] = vals
+				case reflect.Pointer:
```
Comment (jmorganca) [inline api/types.go:605]: I'm not sure if we need this – similar fields such as `stream` seem to work okay without it.

File: api/types.go [hunk 2]
```diff
@@ -538,7 +505,7 @@ func DefaultOptions() Options {
 			LowVRAM:   false,
 			F16KV:     true,
 			UseMLock:  false,
-			UseMMap:   TriStateUndefined,
+			UseMMap:   nil,
```
Comment (jmorganca) [inline api/types.go:508]: I think we can keep this `true` (if we want it on by default that is). Otherwise we can just omit this from the struct as it will default to `nil`

File: llm/server.go [hunk 3]
```diff
@@ -208,7 +208,8 @@ func NewLlamaServer(gpus gpu.GpuInfoList, model string, ggml *GGML, adapters, pr
 		if g.Library == "metal" &&
 			uint64(opts.NumGPU) > 0 &&
 			uint64(opts.NumGPU) < ggml.KV().BlockCount()+1 {
-			opts.UseMMap = api.TriStateFalse
+			noMMap := false
```
Comment (jmorganca) [inline llm/server.go:211]: I believe this should work to create a `*bool` set to false

```
opts.UseMMap = new(bool)
```

**Review by jmorganca — COMMENTED** [review]
LGTM, just a few comments that might help tidy this up

File: api/types.go (hunk 1 above)
Comment (jmorganca) [reply api/types.go:605]: Ah I see this is for parsing the options.

File: api/types.go (hunk 2 above)
Comment (dhiltgen) [reply api/types.go:508]: We need the default to be unset in order to detect if the client actually passes in a true or false, or just leaves it blank.  Otherwise we can't have the [use-case specific default behavior logic](https://github.com/ollama/ollama/blob/main/llm/server.go#L219-L227)  As to the pedantic nil, yes, we could omit it, but since it's treated as a bool largely, I thought it good to be explicit so it's not ambiguous as a false for better readability of the code.

**Review by jmorganca — APPROVED** [review]
