### PR TITLE
Make stall duration timeout configurable

### LINKED ISSUE #6031: Timeout to start model too little - progress stalls at 100% for 5 minutes when loading with swap
### What is the issue?

I am trying to run llama:405b on a hardware with only little power and through a swap file.
Im not concerned about its speed.
Though, the Model cant load because:
```
ollama run llama3.1:405b --keepalive 5h
Error: timed out waiting for llama runner to start - progress 1.00 -
``` 

is it possible to disable this timeout, or increase it? Im quite certain it would load after (a long) while

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3.0

### PR DESCRIPTION
**Pull request by dhiltgen**
With the new very large parameter models, some users are willing to wait for a very long time for models to load.

Fixes #6031

### CODE REVIEW

File: envconfig/config.go [hunk 1]
```diff
@@ -112,6 +112,26 @@ func KeepAlive() (keepAlive time.Duration) {
 	return keepAlive
 }
 
+// LoadTimeout returns the duration for stall detection during model loads. LoadTimeout can be configured via the OLLAMA_LOAD_TIMEOUT environment variable.
+// Zero or Negative values are treated as infinite.
+// Default is 5 minutes.
+func LoadTimeout() (loadTimeout time.Duration) {
+	loadTimeout = 5 * time.Minute
+	if s := Var("OLLAMA_LOAD_TIMEOUT"); s != "" {
+		if d, err := time.ParseDuration(s); err == nil {
```
Comment (jmorganca) [inline envconfig/config.go:121]: Do we have a standard function anywhere for parsing Ollama "durations" (i.e. time.Duration || seconds)

**Review by jmorganca — APPROVED** [review]
LGTM. A light unit test here would be great!

**Comment by jmorganca** [comment]
possible to name the squashed commit something like

```
llm: make load time stall duration configurable via OLLAMA_LOAD_TIMEOUT
```
