### PR TITLE
Better support for AMD multi-GPU on linux

### LINKED ISSUE #5143: AMD iGPU works in docker with override but not on host
### What is the issue?

Ollama is failing to run on GPU instead it uses CPU. If I force it using `HSA_OVERRIDE_GFX_VERSION=9.0.0` then I get  `Error: llama runner process has terminated: signal: aborted error:Could not initialize Tensile host: No devices found`. 

## ENV:
I'm using Proxmox LXC with Device Passthrough.  

## journalctl:
```
Jun 19 14:38:07 ai-llm systemd[1]: Stopping Ollama Service...
Jun 19 14:38:07 ai-llm systemd[1]: ollama.service: Deactivated successfully.
Jun 19 14:38:07 ai-llm systemd[1]: Stopped Ollama Service.
Jun 19 14:38:07 ai-llm systemd[1]: ollama.service: Consumed 7.818s CPU time.
Jun 19 14:38:07 ai-llm systemd[1]: Started Ollama Service.
Jun 19 14:38:07 ai-llm ollama[15932]: 2024/06/19 14:38:07 routes.go:1011: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.>
Jun 19 14:38:07 ai-llm ollama[15932]: time=2024-06-19T14:38:07.789Z level=INFO source=images.go:725 msg="total blobs: 5"
Jun 19 14:38:07 ai-llm ollama[15932]: time=2024-06-19T14:38:07.789Z level=INFO source=images.go:732 msg="total unused blobs removed: 0"
Jun 19 14:38:07 ai-llm ollama[15932]: time=2024-06-19T14:38:07.789Z level=INFO source=routes.go:1057 msg="Listening on 127.0.0.1:11434 (version 0.1.44)"
Jun 19 14:38:07 ai-llm ollama[15932]: time=2024-06-19T14:38:07.789Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama3886990766/runners
Jun 19 14:38:10 ai-llm ollama[15932]: time=2024-06-19T14:38:10.123Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cuda_v11 rocm_v60002 cpu]"
Jun 19 14:38:10 ai-llm ollama[15932]: time=2024-06-19T14:38:10.125Z level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-dri>
Jun 19 14:38:10 ai-llm ollama[15932]: time=2024-06-19T14:38:10.126Z level=INFO source=amd_linux.go:304 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=9.0.0
Jun 19 14:38:10 ai-llm ollama[15932]: time=2024-06-19T14:38:10.126Z level=INFO source=types.go:71 msg="inference compute" id=0 library=rocm compute=gfx90c driver=0.0 name=1002:1>
Jun 19 14:38:12 ai-llm ollama[15932]: [GIN] 2024/06/19 - 14:38:12 | 200 |      39.044<C2><B5>s |       127.0.0.1 | HEAD     "/"
Jun 19 14:38:12 ai-llm ollama[15932]: [GIN] 2024/06/19 - 14:38:12 | 200 |     436.745<C2><B5>s |       127.0.0.1 | POST     "/api/show"
Jun 19 14:38:12 ai-llm ollama[15932]: [GIN] 2024/06/19 - 14:38:12 | 200 |     278.824<C2><B5>s |       127.0.0.1 | POST     "/api/show"
Jun 19 14:38:12 ai-llm ollama[15932]: time=2024-06-19T14:38:12.873Z level=WARN source=amd_linux.go:48 msg="ollama recommends running the https://www.amd.com/en/support/linux-dri>
Jun 19 14:38:12 ai-llm ollama[15932]: time=2024-06-19T14:38:12.874Z level=INFO source=amd_linux.go:304 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=9.0.0
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.183Z level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=23 memory.available="8.0>
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.183Z level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=23 memory.available="8.0>
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.184Z level=INFO source=server.go:341 msg="starting llama server" cmd="/tmp/ollama3886990766/runners/rocm_v60002/ol>
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.184Z level=INFO source=sched.go:338 msg="loaded runners" count=1
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.184Z level=INFO source=server.go:529 msg="waiting for llama runner to start responding"
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.185Z level=INFO source=server.go:567 msg="waiting for server to become available" status="llm server error"
Jun 19 14:38:13 ai-llm ollama[15955]: INFO [main] build info | build=1 commit="5921b8f" tid="125536033915712" timestamp=1718807893
Jun 19 14:38:13 ai-llm ollama[15955]: INFO [main] system info | n_threads=8 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AV>
Jun 19 14:38:13 ai-llm ollama[15955]: INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="7" port="44261" tid="125536033915712" timestamp=1718807893
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: loaded meta data with 23 key-value pairs and 201 tensors from /usr/share/ollama/.ollama/models/blobs/sha256-2af3b81862c>
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   0:                       general.architecture str              = llama
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   1:                               general.name str              = TinyLlama
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   2:                       llama.context_length u32              = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   3:                     llama.embedding_length u32              = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   4:                          llama.block_count u32              = 22
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 5632
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 64
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 4
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  11:                          general.file_type u32              = 2
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,61249]   = ["<E2><96><81> t", "e r", "i n", "<E2><96><81> >
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 1
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32              = 2
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  19:            tokenizer.ggml.unknown_token_id u32              = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  20:            tokenizer.ggml.padding_token_id u32              = 2
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {% for message in messages %}\n{% if m...
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - kv  22:               general.quantization_version u32              = 2
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - type  f32:   45 tensors
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - type q4_0:  155 tensors
Jun 19 14:38:13 ai-llm ollama[15932]: llama_model_loader: - type q6_K:    1 tensors
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_vocab: special tokens cache size = 259
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_vocab: token to piece cache size = 0.3368 MB
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: format           = GGUF V3 (latest)
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: arch             = llama
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: vocab type       = SPM
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_vocab          = 32000
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_merges         = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_ctx_train      = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_embd           = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_head           = 32
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_head_kv        = 4
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_layer          = 22
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_rot            = 64
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_embd_head_k    = 64
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_embd_head_v    = 64
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_gqa            = 8
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_embd_k_gqa     = 256
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_embd_v_gqa     = 256
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: f_norm_eps       = 0.0e+00
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: f_clamp_kqv      = 0.0e+00
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: f_max_alibi_bias = 0.0e+00
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: f_logit_scale    = 0.0e+00
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_ff             = 5632
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_expert         = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_expert_used    = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: causal attn      = 1
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: pooling type     = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: pooling type     = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: rope type        = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: rope scaling     = linear
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: freq_base_train  = 10000.0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: freq_scale_train = 1
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_yarn_orig_ctx  = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: rope_finetuned   = unknown
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_d_conv       = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_d_inner      = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: freq_base_train  = 10000.0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: freq_scale_train = 1
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: n_yarn_orig_ctx  = 2048
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: rope_finetuned   = unknown
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_d_conv       = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_d_inner      = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_d_state      = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: ssm_dt_rank      = 0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: model type       = 1B
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: model ftype      = Q4_0
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: model params     = 1.10 B
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: model size       = 606.53 MiB (4.63 BPW)
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: general.name     = TinyLlama
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: BOS token        = 1 '<s>'
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: EOS token        = 2 '</s>'
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: UNK token        = 0 '<unk>'
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: PAD token        = 2 '</s>'
Jun 19 14:38:13 ai-llm ollama[15932]: llm_load_print_meta: LF token         = 13 '<0x0A>'
Jun 19 14:38:13 ai-llm ollama[15932]: rocBLAS error: Could not initialize Tensile host: No devices found
Jun 19 14:38:13 ai-llm ollama[15932]: time=2024-06-19T14:38:13.436Z level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: >
```

## rocm-smi
```
============================================ ROCm System Management Interface ============================================
====================================================== Concise Info ======================================================
Device  Node  IDs              Temp    Power     Partitions          SCLK  MCLK     Fan  Perf  PwrCap       VRAM%  GPU%  
              (DID,     GUID)  (Edge)  (Socket)  (Mem, Compute, ID)                                                      
==========================================================================================================================
0       1     0x164c,   28495  46.0°C  9.0W      N/A, N/A, 0         None  1200Mhz  0%   auto  Unsupported  1%     0%    
==========================================================================================================================
================================================== End of ROCm SMI Log ===================================================
```

## rocminfo
```
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 5700U with Radeon Graphics
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 7 5700U with Radeon Graphics
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4372                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            16                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    24508068(0x175f6a4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    24508068(0x175f6a4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    24508068(0x175f6a4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx90c                             
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      1024(0x400) KB                     
  Chip ID:                 5708(0x164c)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1900                               
  BDFID:                   1024                               
  Internal Node ID:        1                                  
  Compute Unit:            8                                  
  SIMDs per CU:            4                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 471                                
  SDMA engine uCode::      40                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608(0x800000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    8388608(0x800000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90c:xnack-   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```

## rocm version 
```
Package: rocm-libs
Version: 6.1.1.60101-90~22.04
Priority: optional
Section: devel
Maintainer: ROCm Dev Support <rocm-dev.support@amd.com>
Installed-Size: 13.3 kB
Depends: hipblas (= 2.1.0.60101-90~22.04), hipblaslt (= 0.7.0.60101-90~22.04), hipfft (= 1.0.14.60101-90~22.04), hipsolver (= 2.1.1.60101-90~22.04), hipsparse (= 3.0.1.60101-90~22.04), hiptensor (= 1.2.0.60101-90~22.04), miopen-hip (= 3.1.0.60101-90~22.04), half (= 1.12.0.60101-90~22.04), rccl (= 2.18.6.60101-90~22.04), rocalution (= 3.1.1.60101-90~22.04), rocblas (= 4.1.0.60101-90~22.04), rocfft (= 1.0.27.60101-90~22.04), rocrand (= 3.0.1.60101-90~22.04), hiprand (= 2.10.16.60101-90~22.04), rocsolver (= 3.25.0.60101-90~22.04), rocsparse (= 3.1.2.60101-90~22.04), rocm-core (= 6.1.1.60101-90~22.04), hipsparselt (= 0.1.0.60101-90~22.04), composablekernel-dev (= 1.1.0.60101-90~22.04), hipblas-dev (= 2.1.0.60101-90~22.04), hipblaslt-dev (= 0.7.0.60101-90~22.04), hipcub-dev (= 3.1.0.60101-90~22.04), hipfft-dev (= 1.0.14.60101-90~22.04), hipsolver-dev (= 2.1.1.60101-90~22.04), hipsparse-dev (= 3.0.1.60101-90~22.04), hiptensor-dev (= 1.2.0.60101-90~22.04), miopen-hip-dev (= 3.1.0.60101-90~22.04), rccl-dev (= 2.18.6.60101-90~22.04), rocalution-dev (= 3.1.1.60101-90~22.04), rocblas-dev (= 4.1.0.60101-90~22.04), rocfft-dev (= 1.0.27.60101-90~22.04), rocprim-dev (= 3.1.0.60101-90~22.04), rocrand-dev (= 3.0.1.60101-90~22.04), hiprand-dev (= 2.10.16.60101-90~22.04), rocsolver-dev (= 3.25.0.60101-90~22.04), rocsparse-dev (= 3.1.2.60101-90~22.04), rocthrust-dev (= 3.0.1.60101-90~22.04), rocwmma-dev (= 1.4.0.60101-90~22.04), hipsparselt-dev (= 0.1.0.60101-90~22.04)
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 1060 B
APT-Sources: https://repo.radeon.com/rocm/apt/6.1.1 jammy/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack
```

## Troubleshooting?
1. I tried to `HSA_OVERRIDE_GFX_VERSION=9.0.0` + `HIP_VISIBLE_DEVICES=0` to the service file but it didn't change anything. 

2. I tried to run ollama using docker in proxmox LXC, with device passthrough using this cmd 
```
docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama --device=/dev/kfd --device=/dev/dri/renderD128 --env HSA_OVERRIDE_GFX_VERSION=9.0.0 --env HSA_ENABLE_SDMA=0 ollama/ollama:rocm
```

everything works as expected. 

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.44

### LINKED ISSUE #6304: Latest version (0.3.4) not detecting AMD GPUs (Instinct MI210)
The latest version of Ollama (0.3.4) is not detecting or utilizing AMD GPUs (Instinct MI210) when run in a Docker container.

I tried to run it with docker because I didn't want to update the Ollama working version for me 0.2.8.

I followed the instruction here: https://hub.docker.com/r/ollama/ollama.

command ```docker run -d --device /dev/kfd --device /dev/dri -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:rocm```

Please see below the error (I tried as well before to update the Ollama with the latest version on my server but encountered the same issue)

Any insights or suggestions would be greatly appreciated!

```
[genai1~]$ docker exec 92ebd80dcef1 /opt/rocm/bin/rocm-smi
========================================== ROCm System Management Interface ==========================================
==================================================== Concise Info ====================================================
Device  Node  IDs              Temp    Power   Partitions          SCLK     MCLK     Fan  Perf  PwrCap  VRAM%  GPU%  
              (DID,     GUID)  (Edge)  (Avg)   (Mem, Compute, ID)                                                    
======================================================================================================================
Traceback (most recent call last):
  File "/opt/rocm/bin/rocm-smi", line 4074, in <module>
    showAllConcise(deviceList)
  File "/opt/rocm/bin/rocm-smi", line 2033, in showAllConcise
    zip(range(len(max_widths)), values['card%s' % (str(device))])), None)
  File "/opt/rocm/bin/rocm-smi", line 872, in printLog
    print(logstr + '\n', end='')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 35: ordinal not in range(128)
```
```
[genai1~]$ docker exec 92ebd80dcef1 ls -la /root/.ollama
total 20
drwxr-xr-x 3 root root 4096 Aug 10 19:17 .
dr-xr-x--- 1 root root 4096 Aug 10 19:46 ..
-rw------- 1 root root  387 Aug 10 19:17 id_ed25519
-rw-r--r-- 1 root root   81 Aug 10 19:17 id_ed25519.pub
drwxr-xr-x 4 root root 4096 Aug 10 19:55 models
[genai1~]$ docker logs 92ebd80dcef1
2docker logs 92ebd80dcef1
2024/08/10 19:46:51 routes.go:1108: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-08-10T19:46:51.654Z level=INFO source=images.go:781 msg="total blobs: 0"
time=2024-08-10T19:46:51.654Z level=INFO source=images.go:788 msg="total unused blobs removed: 0"
time=2024-08-10T19:46:51.654Z level=INFO source=routes.go:1155 msg="Listening on [::]:11434 (version 0.3.4)"
time=2024-08-10T19:46:51.655Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama2612956243/runners
time=2024-08-10T19:46:54.488Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cuda_v11 rocm_v60102 cpu cpu_avx cpu_avx2]"
time=2024-08-10T19:46:54.488Z level=INFO source=gpu.go:204 msg="looking for compatible GPUs"
time=2024-08-10T19:46:54.491Z level=WARN source=amd_linux.go:59 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-08-10T19:46:54.491Z level=INFO source=amd_linux.go:274 msg="unsupported Radeon iGPU detected skipping" id=0 total="0 B"
time=2024-08-10T19:46:54.492Z level=INFO source=amd_linux.go:274 msg="unsupported Radeon iGPU detected skipping" id=1 total="0 B"
time=2024-08-10T19:46:54.492Z level=INFO source=amd_linux.go:274 msg="unsupported Radeon iGPU detected skipping" id=2 total="0 B"
time=2024-08-10T19:46:54.492Z level=INFO source=amd_linux.go:274 msg="unsupported Radeon iGPU detected skipping" id=3 total="0 B"
time=2024-08-10T19:46:54.492Z level=INFO source=amd_linux.go:360 msg="no compatible amdgpu devices detected"
time=2024-08-10T19:46:54.492Z level=INFO source=gpu.go:347 msg="no compatible GPUs were discovered"
time=2024-08-10T19:46:54.492Z level=INFO source=types.go:105 msg="inference compute" id=0 library=cpu compute="" driver=0.0 name="" total="250.9 GiB" available="230.3 GiB"

Error: something went wrong, please see the ollama server logs for details
[genai1~]$ docker exec 92ebd80dcef1 env | grep OLLAMA
OLLAMA_HOST=0.0.0.0
[genai1~]$ docker exec 92ebd80dcef1 ls -l /opt/rocm/bin
total 78928
-rwxr-xr-x 1 root root  3993744 May 28 21:10 MIOpenDriver
lrwxrwxrwx 1 root root       35 Jun 10 14:56 amd-smi -> ../libexec/amdsmi_cli/amdsmi_cli.py
lrwxrwxrwx 1 root root       24 Jun 10 14:51 amdclang -> ../lib/llvm/bin/amdclang
lrwxrwxrwx 1 root root       26 Jun 10 14:51 amdclang++ -> ../lib/llvm/bin/amdclang++
lrwxrwxrwx 1 root root       27 Jun 10 14:51 amdclang-cl -> ../lib/llvm/bin/amdclang-cl
lrwxrwxrwx 1 root root       28 Jun 10 14:51 amdclang-cpp -> ../lib/llvm/bin/amdclang-cpp
lrwxrwxrwx 1 root root       24 Jun 10 14:51 amdflang -> ../lib/llvm/bin/amdflang
lrwxrwxrwx 1 root root       22 Jun 10 14:51 amdlld -> ../lib/llvm/bin/amdlld
lrwxrwxrwx 1 root root       22 Jun 10 14:53 aompcc -> ../lib/llvm/bin/aompcc
-rwxr-xr-x 1 root root   107592 May 28 19:14 clinfo
-rwxrwxr-x 1 root root     2551 May 28 18:08 hipcc
-rwxr-xr-x 1 root root   575472 May 28 18:11 hipcc.bin
-rwxrwxr-x 1 root root    21889 May 28 18:08 hipcc.pl
-rwxrwxr-x 1 root root     1508 May 28 18:08 hipcc_cmake_linker_helper
-rwxrwxr-x 1 root root     2453 May 28 18:08 hipconfig
-rwxr-xr-x 1 root root   575480 May 28 18:11 hipconfig.bin
-rwxrwxr-x 1 root root     7539 May 28 18:08 hipconfig.pl
-rwxr-xr-x 1 root root      784 May 28 18:08 hipconvertinplace-perl.sh
-rwxr-xr-x 1 root root      674 May 28 18:08 hipconvertinplace.sh
-rwxrwxr-x 1 root root     1857 May 28 18:08 hipdemangleatp
-rwxr-xr-x 1 root root      407 May 28 18:08 hipexamine-perl.sh
-rwxr-xr-x 1 root root      557 May 28 18:08 hipexamine.sh
-rwxr-xr-x 1 root root 62142024 May 28 19:14 hipify-clang
-rwxr-xr-x 1 root root   659191 May 28 18:08 hipify-perl
-rw-rw-r-- 1 root root     6486 May 28 18:08 hipvars.pm
-rwxr-xr-x 1 root root     1332 May 28 19:30 install_precompiled_kernels.sh
lrwxrwxrwx 1 root root       21 Jun 10 14:53 mygpu -> ../lib/llvm/bin/mygpu
lrwxrwxrwx 1 root root       22 Jun 10 14:53 mymcpu -> ../lib/llvm/bin/mymcpu
lrwxrwxrwx 1 root root       28 Jun 10 14:51 offload-arch -> ../lib/llvm/bin/offload-arch
-rwxrwxr-x 1 root root    10047 May 28 18:08 roc-obj
-rwxrwxr-x 1 root root     8457 May 28 18:08 roc-obj-extract
-rwxrwxr-x 1 root root       71 May 28 18:08 roc-obj-extract.bat
-rwxrwxr-x 1 root root     6973 May 28 18:08 roc-obj-ls
-rwxrwxr-x 1 root root       56 May 28 18:08 roc-obj-ls.bat
-rwxr-xr-x 1 root root 12314744 May 28 18:57 rocgdb
lrwxrwxrwx 1 root root       31 Jun 10 14:52 rocm-smi -> ../libexec/rocm_smi/rocm_smi.py
-rwxr-xr-x 1 root root    10057 May 28 18:50 rocm_agent_enumerator
-rwxr-xr-x 1 root root   159560 May 28 18:50 rocminfo
-r-xr-xr-x 1 root root    22019 May 28 18:08 rocprof
-r-xr-xr-x 1 root root    11523 May 28 18:08 rocprofv2
-rwxr-xr-x 1 root root    96000 May 28 19:17 rocsys
-rwxr-xr-x 1 root root     9224 May 28 19:30 test_perf.py
[genai1@~]$ docker exec 92ebd80dcef1 ls -l /opt/rocm/lib
total 10486408
drwxr-xr-x 32 root root       4096 Jun 10 14:56 cmake
drwxr-xr-x  3 root root       4096 Jun 10 14:55 hipblaslt
drwxr-xr-x  3 root root       4096 Jun 10 14:54 hipsparselt
drwxr-xr-x  2 root root       4096 Jun 10 14:52 hsa-amd-aqlprofile
lrwxrwxrwx  1 root root         14 Jun 10 14:55 libMIOpen.so -> libMIOpen.so.1
lrwxrwxrwx  1 root root         22 Jun 10 14:54 libMIOpen.so.1 -> libMIOpen.so.1.0.60102
-rwxr-xr-x  1 root root 1120623856 May 28 21:10 libMIOpen.so.1.0.60102
lrwxrwxrwx  1 root root         14 Jun 10 14:52 libOpenCL.so -> libOpenCL.so.1
lrwxrwxrwx  1 root root         16 Jun 10 14:52 libOpenCL.so.1 -> libOpenCL.so.1.2
-rwxr-xr-x  1 root root      36968 May 28 19:13 libOpenCL.so.1.2
lrwxrwxrwx  1 root root         17 Jun 10 14:51 libamd_comgr.so -> libamd_comgr.so.2
lrwxrwxrwx  1 root root         25 Jun 10 14:51 libamd_comgr.so.2 -> libamd_comgr.so.2.7.60102
-rwxr-xr-x  1 root root  149865832 May 28 18:50 libamd_comgr.so.2.7.60102
lrwxrwxrwx  1 root root         16 Jun 10 14:56 libamd_smi.so -> libamd_smi.so.24
lrwxrwxrwx  1 root root         24 Jun 10 14:56 libamd_smi.so.24 -> libamd_smi.so.24.5.60102
-rwxr-xr-x  1 root root    1664088 May 28 18:11 libamd_smi.so.24.5.60102
lrwxrwxrwx  1 root root         16 Jun 10 14:53 libamdhip64.so -> libamdhip64.so.6
-rwxr-xr-x  1 root root   23232120 Oct  6  2023 libamdhip64.so.5
lrwxrwxrwx  1 root root         24 Jun 10 14:53 libamdhip64.so.6 -> libamdhip64.so.6.1.60102
-rwxr-xr-x  1 root root   27904952 May 28 19:13 libamdhip64.so.6.1.60102
-rwxr-xr-x  1 root root    1531472 May 28 19:14 libamdocl64.so
-rw-r--r--  1 root root  295230498 May 28 19:46 libdevice_contraction_operations.a
-rw-r--r--  1 root root 1367985582 May 28 19:46 libdevice_conv_operations.a
-rw-r--r--  1 root root 1908049166 May 28 19:46 libdevice_gemm_operations.a
-rw-r--r--  1 root root  376043220 May 28 19:46 libdevice_other_operations.a
-rw-r--r--  1 root root 1074021278 May 28 19:47 libdevice_reduction_operations.a
lrwxrwxrwx  1 root root         15 Jun 10 14:56 libhipblas.so -> libhipblas.so.2
lrwxrwxrwx  1 root root         23 Jun 10 14:54 libhipblas.so.2 -> libhipblas.so.2.1.60102
-rwxr-xr-x  1 root root    1073688 May 28 21:09 libhipblas.so.2.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:56 libhipblaslt.so -> libhipblaslt.so.0
lrwxrwxrwx  1 root root         25 Jun 10 14:54 libhipblaslt.so.0 -> libhipblaslt.so.0.7.60102
-rwxr-xr-x  1 root root    9946264 May 28 22:46 libhipblaslt.so.0.7.60102
lrwxrwxrwx  1 root root         14 Jun 10 14:52 libhipfft.so -> libhipfft.so.0
lrwxrwxrwx  1 root root         22 Jun 10 14:52 libhipfft.so.0 -> libhipfft.so.0.1.60102
-rwxr-xr-x  1 root root      61832 May 28 21:51 libhipfft.so.0.1.60102
lrwxrwxrwx  1 root root         15 Jun 10 14:52 libhiprand.so -> libhiprand.so.1
lrwxrwxrwx  1 root root         23 Jun 10 14:52 libhiprand.so.1 -> libhiprand.so.1.1.60102
-rwxr-xr-x  1 root root      18440 May 28 19:51 libhiprand.so.1.1.60102
lrwxrwxrwx  1 root root         23 Jun 10 14:53 libhiprtc-builtins.so -> libhiprtc-builtins.so.6
lrwxrwxrwx  1 root root         31 Jun 10 14:53 libhiprtc-builtins.so.6 -> libhiprtc-builtins.so.6.1.60102
-rwxr-xr-x  1 root root     559736 May 28 19:13 libhiprtc-builtins.so.6.1.60102
lrwxrwxrwx  1 root root         14 Jun 10 14:53 libhiprtc.so -> libhiprtc.so.6
lrwxrwxrwx  1 root root         22 Jun 10 14:53 libhiprtc.so.6 -> libhiprtc.so.6.1.60102
-rwxr-xr-x  1 root root     918128 May 28 19:13 libhiprtc.so.6.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:56 libhipsolver.so -> libhipsolver.so.0
lrwxrwxrwx  1 root root         25 Jun 10 14:56 libhipsolver.so.0 -> libhipsolver.so.0.1.60102
-rwxr-xr-x  1 root root     307056 May 28 21:09 libhipsolver.so.0.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:56 libhipsparse.so -> libhipsparse.so.1
lrwxrwxrwx  1 root root         27 Jun 10 14:54 libhipsparse.so.1 -> libhipsparse.so.1.0.0.60102
-rwxr-xr-x  1 root root     312176 May 28 20:01 libhipsparse.so.1.0.0.60102
lrwxrwxrwx  1 root root         19 Jun 10 14:56 libhipsparselt.so -> libhipsparselt.so.0
lrwxrwxrwx  1 root root         27 Jun 10 14:54 libhipsparselt.so.0 -> libhipsparselt.so.0.2.60102
-rwxr-xr-x  1 root root    8293856 May 28 20:08 libhipsparselt.so.0.2.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:52 libhiptensor.so -> libhiptensor.so.0
lrwxrwxrwx  1 root root         25 Jun 10 14:52 libhiptensor.so.0 -> libhiptensor.so.0.1.60102
-rwxr-xr-x  1 root root  334544520 May 28 20:09 libhiptensor.so.0.1.60102
lrwxrwxrwx  1 root root         28 Jun 10 14:52 libhsa-amd-aqlprofile64.so -> libhsa-amd-aqlprofile64.so.1
lrwxrwxrwx  1 root root         36 Jun 10 14:52 libhsa-amd-aqlprofile64.so.1 -> libhsa-amd-aqlprofile64.so.1.0.60102
-rwxr-xr-x  1 root root     583088 May 28 18:50 libhsa-amd-aqlprofile64.so.1.0.60102
lrwxrwxrwx  1 root root         21 Jun 10 14:52 libhsa-runtime64.so -> libhsa-runtime64.so.1
lrwxrwxrwx  1 root root         30 Jun 10 14:52 libhsa-runtime64.so.1 -> libhsa-runtime64.so.1.13.60102
-rwxr-xr-x  1 root root    3089448 May 28 18:50 libhsa-runtime64.so.1.13.60102
-rwxr-xr-x  1 root root     275208 May 28 18:10 libhsakmt.a
lrwxrwxrwx  1 root root         11 Jun 10 14:52 liboam.so -> liboam.so.1
lrwxrwxrwx  1 root root         19 Jun 10 14:52 liboam.so.1 -> liboam.so.1.0.60102
-rwxr-xr-x  1 root root    1383936 May 28 18:11 liboam.so.1.0.60102
lrwxrwxrwx  1 root root         12 Jun 10 14:55 librccl.so -> librccl.so.1
lrwxrwxrwx  1 root root         20 Jun 10 14:55 librccl.so.1 -> librccl.so.1.0.60102
-rwxr-xr-x  1 root root  231504192 May 28 19:52 librccl.so.1.0.60102
lrwxrwxrwx  1 root root         18 Jun 10 14:55 librocalution.so -> librocalution.so.1
lrwxrwxrwx  1 root root         26 Jun 10 14:54 librocalution.so.1 -> librocalution.so.1.0.60102
-rwxr-xr-x  1 root root   11570680 May 28 21:07 librocalution.so.1.0.60102
lrwxrwxrwx  1 root root         22 Jun 10 14:55 librocalution_hip.so -> librocalution_hip.so.1
lrwxrwxrwx  1 root root         32 Jun 10 14:54 librocalution_hip.so.1 -> librocalution_hip.so.1.0.0.60102
-rwxr-xr-x  1 root root   75440704 May 28 21:07 librocalution_hip.so.1.0.0.60102
lrwxrwxrwx  1 root root         15 Jun 10 14:56 librocblas.so -> librocblas.so.4
lrwxrwxrwx  1 root root         23 Jun 10 14:53 librocblas.so.4 -> librocblas.so.4.1.60102
-rwxr-xr-x  1 root root  881735968 May 28 21:00 librocblas.so.4.1.60102
lrwxrwxrwx  1 root root         14 Jun 10 14:52 librocfft.so -> librocfft.so.0
lrwxrwxrwx  1 root root         22 Jun 10 14:51 librocfft.so.0 -> librocfft.so.0.1.60102
-rwxr-xr-x  1 root root   10736160 May 28 19:55 librocfft.so.0.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:51 librocm-core.so -> librocm-core.so.1
lrwxrwxrwx  1 root root         25 Jun 10 14:51 librocm-core.so.1 -> librocm-core.so.1.0.60102
-rwxr-xr-x  1 root root      17000 May 28 19:21 librocm-core.so.1.0.60102
lrwxrwxrwx  1 root root         19 Jun 10 14:51 librocm-dbgapi.so -> librocm-dbgapi.so.0
lrwxrwxrwx  1 root root         24 Jun 10 14:51 librocm-dbgapi.so.0 -> librocm-dbgapi.so.0.71.0
-rwxr-xr-x  1 root root    1185632 May 28 18:51 librocm-dbgapi.so.0.71.0
lrwxrwxrwx  1 root root         28 Jun 10 14:52 librocm-debug-agent.so.2 -> librocm-debug-agent.so.2.0.3
-rwxr-xr-x  1 root root     151368 May 28 19:13 librocm-debug-agent.so.2.0.3
lrwxrwxrwx  1 root root         18 Jun 10 14:52 librocm_smi64.so -> librocm_smi64.so.7
lrwxrwxrwx  1 root root         26 Jun 10 14:52 librocm_smi64.so.7 -> librocm_smi64.so.7.2.60102
-rwxr-xr-x  1 root root    1363256 May 28 18:11 librocm_smi64.so.7.2.60102
lrwxrwxrwx  1 root root         28 Jun 10 14:52 librocprofiler-register.so -> librocprofiler-register.so.0
lrwxrwxrwx  1 root root         32 Jun 10 14:52 librocprofiler-register.so.0 -> librocprofiler-register.so.0.3.0
-rwxr-xr-x  1 root root    1049792 May 28 18:11 librocprofiler-register.so.0.3.0
lrwxrwxrwx  1 root root         21 Jun 10 14:56 librocprofiler64.so -> librocprofiler64.so.1
lrwxrwxrwx  1 root root         29 Jun 10 14:56 librocprofiler64.so.1 -> librocprofiler64.so.1.0.60102
-rwxr-xr-x  1 root root     334944 May 28 19:17 librocprofiler64.so.1.0.60102
lrwxrwxrwx  1 root root         29 Jun 10 14:56 librocprofiler64.so.2 -> librocprofiler64.so.2.0.60102
-rwxr-xr-x  1 root root    1129944 May 28 19:17 librocprofiler64.so.2.0.60102
lrwxrwxrwx  1 root root         21 Jun 10 14:56 librocprofiler64v2.so -> librocprofiler64.so.2
lrwxrwxrwx  1 root root         15 Jun 10 14:52 librocrand.so -> librocrand.so.1
lrwxrwxrwx  1 root root         23 Jun 10 14:52 librocrand.so.1 -> librocrand.so.1.1.60102
-rwxr-xr-x  1 root root   62393304 May 28 19:45 librocrand.so.1.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:56 librocsolver.so -> librocsolver.so.0
lrwxrwxrwx  1 root root         25 Jun 10 14:54 librocsolver.so.0 -> librocsolver.so.0.1.60102
-rwxr-xr-x  1 root root 1384333400 May 28 21:05 librocsolver.so.0.1.60102
lrwxrwxrwx  1 root root         17 Jun 10 14:56 librocsparse.so -> librocsparse.so.1
lrwxrwxrwx  1 root root         25 Jun 10 14:54 librocsparse.so.1 -> librocsparse.so.1.0.60102
-rwxr-xr-x  1 root root 1367043336 May 28 19:52 librocsparse.so.1.0.60102
lrwxrwxrwx  1 root root         19 Jun 10 14:52 libroctracer64.so -> libroctracer64.so.4
lrwxrwxrwx  1 root root         27 Jun 10 14:52 libroctracer64.so.4 -> libroctracer64.so.4.1.60102
-rwxr-xr-x  1 root root     321512 May 28 19:14 libroctracer64.so.4.1.60102
lrwxrwxrwx  1 root root         15 Jun 10 14:52 libroctx64.so -> libroctx64.so.4
lrwxrwxrwx  1 root root         23 Jun 10 14:52 libroctx64.so.4 -> libroctx64.so.4.1.60102
-rwxr-xr-x  1 root root      15360 May 28 19:14 libroctx64.so.4.1.60102
-rw-r--r--  1 root root      38898 May 28 19:46 libutility.a
drwxr-xr-x  7 root root       4096 Jun 10 14:53 llvm
drwxr-xr-x  2 root root       4096 Jun 10 14:53 pkgconfig
drwxr-xr-x  3 root root       4096 Jun 10 14:53 rocblas
drwxr-xr-x  3 root root       4096 Jun 10 14:52 rocfft
-rw-r--r--  1 root root        512 May 28 19:21 rocmmod
drwxr-xr-x  2 root root       4096 Jun 10 14:56 rocprofiler
drwxr-xr-x  2 root root       4096 Jun 10 14:52 roctracer
[genai1~]$ docker exec 92ebd80dcef1 /opt/rocm/bin/rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          NO

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Xeon(R) Gold 5416S        
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) Gold 5416S        
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    130981244(0x7ce9d7c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    130981244(0x7ce9d7c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    130981244(0x7ce9d7c) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    Intel(R) Xeon(R) Gold 5416S        
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) Gold 5416S        
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4000                               
  BDFID:                   0                                  
  Internal Node ID:        1                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    132109384(0x7dfd448) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    132109384(0x7dfd448) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    132109384(0x7dfd448) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 3                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-12f7490bc7b8aaf0               
  Marketing Name:          AMD Instinct MI210                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29711(0x740f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   19456                              
  Internal Node ID:        2                                  
  Compute Unit:            104                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    2048(0x800)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 82                                 
  SDMA engine uCode::      8                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 4                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-6c2be151a7afe1e5               
  Marketing Name:          AMD Instinct MI210                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    3                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29711(0x740f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   25344                              
  Internal Node ID:        3                                  
  Compute Unit:            104                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    2048(0x800)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 82                                 
  SDMA engine uCode::      8                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 5                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-692c10cf88a75cd5               
  Marketing Name:          AMD Instinct MI210                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    4                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29711(0x740f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   52224                              
  Internal Node ID:        4                                  
  Compute Unit:            104                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    2048(0x800)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 82                                 
  SDMA engine uCode::      8                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 6                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-9d1a65bc110f6055               
  Marketing Name:          AMD Instinct MI210                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    5                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29711(0x740f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   58112                              
  Internal Node ID:        5                                  
  Compute Unit:            104                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    2048(0x800)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 82                                 
  SDMA engine uCode::      8                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```

### OS

Linux

### GPU

AMD

### CPU

_No response_

### Ollama version

0.3.4

### LINKED ISSUE #6595: 4 AMD GPUs with mixed VRAM sizes: layer predictions incorrect leads to runner crash
### What is the issue?

When I load a large model that doesn't fit in VRAM, Ollama crashes:

➜ ~ ollama run dbrx:132b-instruct-q8_0
Error: llama runner process has terminated: signal: segmentation fault (core dumped)

This issue does not occur with Ollama 0.3.6.

My hardware:
CPU: AMD Ryzen Threadripper PRO 7965WX 24-Cores
GPU 1: AMD Instinct MI100 [Discrete]
GPU 2 AMD Instinct MI100 [Discrete]
GPU 3: AMD Radeon RX 6900 XT [Discrete]
GPU 4: AMD Radeon VII [Discrete]
VRAM: 96GiB
RAM: 128 GiB

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.7 - 0.3.9

### LINKED ISSUE #6802: Potential Bug in AMD GPU Detection leading to rocBLAS Initialization Failure
### What is the issue?

This issue happens **randomly**—sometimes the AMD GPU detection works, but at other times, it fails, resulting in the following error 

`rocBLAS error: Could not initialize Tensile host: No devices found.`

When the issue occurs, it seems that certain GPU nodes in the `/sys/class/kfd/kfd/topology/nodes/` directory may not be accessible due to `permission errors.` When these nodes are inaccessible, it might be leading to incorrect GPU indexing. 

The issue might be related to the [AMDGetGPUInfo()](https://github.com/ollama/ollama/blob/56b9af336a049dae37f7cc62246121ac9d18576e/gpu/amd_linux.go#L84) function. This function skips nodes if permission errors occur when reading the properties file see [here](https://github.com/ollama/ollama/blob/56b9af336a049dae37f7cc62246121ac9d18576e/gpu/amd_linux.go#L104), which may cause some GPU nodes to be missed and result in incorrect GPU indexing. 

Below are the output samples for when the GPU detection does not work (non-working case) and when it works as expected (working case).

**Non-Working Output (Failure Case):**

Here’s the output when the rocBLAS error occurs:
```
time=2024-09-09T08:39:19.349Z level=INFO source=gpu.go:200 msg="looking for compatible GPUs"
...
time=2024-09-09T08:39:19.362Z level=INFO source=amd_linux.go:345 msg="amdgpu is supported" gpu=3 gpu_type=gfx942
...
time=2024-09-09T08:39:19.362Z level=INFO source=types.go:107 msg="inference compute" id=3 library=rocm variant="" compute=gfx942 driver=6.7 name=1002:74a1 total="192.0 GiB" available="191.7 GiB"
```
**Notice**, `gpu=3 gpu_type=gfx942`

**Working Output (Success Case):**

Here’s the output  when serving works:
```
2024-09-09T13:55:25.972961384Z time=2024-09-09T13:55:25.972Z level=INFO source=gpu.go:200 msg="looking for compatible GPUs"
2024-09-09T13:55:25.979418720Z time=2024-09-09T13:55:25.979Z level=INFO source=amd_linux.go:345 msg="amdgpu is supported" gpu=0 gpu_type=gfx942
...
...
2024-09-09T13:55:25.979551298Z time=2024-09-09T13:55:25.979Z level=INFO source=types.go:107 msg="inference compute" id=0 library=rocm variant="" compute=gfx942 driver=6.7 name=1002:74a1 total="192.0 GiB" available="191.7 GiB"
```
**Notice**, `gpu=0 gpu_type=gfx942`

**Important information about AMD GPU Drivers:** 

The AMD GPU driver always exposes the host CPU(s) first, but HIP libraries expects zero is the first GPU, not the CPU

**Steps To Reproduce:**
1. Run a Docker container using `ollama/ollama:rocm` on a machine with a single `MI300X`
2. Inside the container, run ollama run llama3.1:70B

Related Discussion:[See](https://github.com/ollama/ollama/issues/6423)

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.9

### PR DESCRIPTION
**Pull request by dhiltgen**
This resolves a number of problems related to AMD multi-GPU setups on linux.

The numeric IDs used by rocm are not the same as the numeric IDs exposed in sysfs although the ordering is consistent.  We have to count up from the first valid gfx (major/minor/patch with non-zero values) we find starting at zero.

There are 3 different env vars for selecting GPUs, and only ROCR_VISIBLE_DEVICES supports UUID based identification, so we should favor that one, and try to use UUIDs if detected to avoid potential ordering bugs with numeric IDs.

Fixes #6595 
Fixes #6304 
Fixes #6802 
Fixes #5143

### CODE REVIEW

File: discover/amd_common.go [hunk 1]
```diff
@@ -47,7 +47,11 @@ func rocmGetVisibleDevicesEnv(gpuInfo []GpuInfo) (string, string) {
 		}
 		ids = append(ids, info.ID)
 	}
-	return "HIP_VISIBLE_DEVICES", strings.Join(ids, ",")
+	// There are 3 potential env vars to use to select GPUs.
+	// ROCR_VISIBLE_DEVICES supports UUID or numeric so is our preferred
+	// GPU_DEVICE_ORDINAL supports numeric IDs only
+	// HIP_VISIBLE_DEVICES supports numeric IDs only
+	return "ROCR_VISIBLE_DEVICES", strings.Join(ids, ",")
```
Comment (jessegross) [inline discover/amd_common.go:54]: Does this cause any backwards compatibility issues for people who are currently setting `HIP_VISIBLE_DEVICES`?

**Review by jessegross — APPROVED** [review]

File: discover/amd_common.go (hunk 1 above)
Comment (dhiltgen) [reply discover/amd_common.go:54]: Good question.  Let me test to see what the behavior is.

Comment (dhiltgen) [reply discover/amd_common.go:54]: It's not ideal.  It winds up masking all the GPUs incorrectly.  Let me clean up that case before we merge this.

Comment (dhiltgen) [reply discover/amd_common.go:54]: fixed

**Comment by dhiltgen** [comment]
Verified on multi-GPU linux and windows setups.
