### PR TITLE
Request and model concurrency

### LINKED ISSUE #961: garbage output on small models spread to many GPUs
when loading a small  model on multiple GPUs, it produces garbage.
the machine has 4 x 3070 (8GB) and an older i5-7400, UBU 22.04, Cuda 11.8

### How to reproduce
starting the server by hand
```bash
ollama serve
```

```bash
ollama run zephyr
>>> why is the sky blue?
acia##############################################################################^C
```

nvidia-smi shows it loads 4 x 1,2 GB

### Workaround
Till we get some flags to control the loading to a discrete GPU
start the server with `CUDA_VISIBLE_DEVICES`
```bash
CUDA_VISIBLE_DEVICES="3" ollama serve # loads the model on GPU No. 4 
```

There seems to be a "memory-low-limit-point", under which this error occures.

### LINKED ISSUE #1514: The code below appears to ignore CUDA_VISIBLE_DEVICES in its calculation, i.e. any GPU you won't use, will still be counted as VRAM.
```go
func CheckVRAM() (int64, error) {
        cmd := exec.Command("nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits")
        var stdout bytes.Buffer
        cmd.Stdout = &stdout
        err := cmd.Run()
        if err != nil {
                return 0, errNvidiaSMI
        }

        var freeMiB int64
        scanner := bufio.NewScanner(&stdout)
        for scanner.Scan() {
                line := scanner.Text()
                if strings.Contains(line, "[Insufficient Permissions]") {
                        return 0, fmt.Errorf("GPU support may not enabled, check you have installed GPU drivers and have the necessary permissions to run nvidia-smi")
                }

                vram, err := strconv.ParseInt(strings.TrimSpace(line), 10, 64)
                if err != nil {
                        return 0, fmt.Errorf("failed to parse available VRAM: %v", err)
                }

                freeMiB += vram
        }

        freeBytes := freeMiB * 1024 * 1024
        if freeBytes < 2*format.GigaByte {
                log.Printf("less than 2 GB VRAM available")
                return 0, errAvailableVRAM
        }

        return freeBytes, nil
}
```

### LINKED ISSUE #1656: Try to use only 1 GPU if possible
I have two GPUs: an RTX 3090 and a 2060. `ollama` tries to split the load among both, but due to communication speed between the cards being significantly slower than within a GPU, this is counterproductive. Would be great to prioritize using the first GPU only, if it alone has enough VRAM to fit the model.

Here are the results of a small experiment:

Model: `solar:q4_0`

- RTX 3090 alone:
  - 350 W: 81 t/s
  - 280W: 79 t/s
- RTX 3090 (280/350 W) and RTX 2060 (128/160 W):
  - 31.5 t/s

To do the test I just changed the value of `CUDA_VISIBLE_DEVICES`  from `0,1` to `0`.

### LINKED ISSUE #2109: Support loading multiple models at the same time
is it possible to create one model from multiple models? or even load multiple models?

### LINKED ISSUE #3304: Bug found ROCm docker (ver 0.1.29) didnt suppot daul CPU, But 0.1.28 is fine w/ Dual CPU
### What is the issue?

**ROCm docker (ver 0.1.29) started well**
time=2024-03-23T04:49:45.409Z level=INFO source=amd_linux.go:50 msg="AMD Driver: 6.3.6"
time=2024-03-23T04:49:45.409Z level=INFO source=amd_linux.go:88 msg="detected amdgpu versions [gfx000 gfx1100]"
time=2024-03-23T04:49:45.423Z level=WARN source=amd_linux.go:114 msg="amdgpu [0] gfx000 is not supported by /tmp/ollama1698492372/rocm [gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942]"
time=2024-03-23T04:49:45.423Z level=WARN source=amd_linux.go:116 msg="See https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md for HSA_OVERRIDE_GFX_VERSION usage"
time=2024-03-23T04:49:45.423Z level=INFO source=amd_linux.go:119 msg="amdgpu [1] gfx1100 is supported"
time=2024-03-23T04:49:45.423Z level=INFO source=amd_linux.go:246 msg="[1] amdgpu totalMemory 20464M"
time=2024-03-23T04:49:45.423Z level=INFO source=amd_linux.go:247 msg="[1] amdgpu freeMemory  20464M"
time=2024-03-23T04:49:45.423Z level=INFO source=amd_common.go:54 msg="Setting HIP_VISIBLE_DEVICES=1"

**BUT running model use CPU always.**

llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   256.00 MiB
llama_new_context_with_model: KV self size  =  256.00 MiB, K (f16):  128.00 MiB, V (f16):  128.00 MiB
llama_new_context_with_model:        CPU input buffer size   =    13.02 MiB
llama_new_context_with_model:        CPU compute buffer size =   160.00 MiB

### What did you expect to see?

Should use ROCm GPU to run model (ROCm-Docker) , not use CPU

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### Architecture

x86

### Platform

Docker

### Ollama version

0.1.29

### GPU

AMD

### GPU info

ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3100                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            20                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    3942924(0x3c2a0c) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    3942924(0x3c2a0c) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    3942924(0x3c2a0c) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3100                               
  BDFID:                   0                                  
  Internal Node ID:        1                                  
  Compute Unit:            20                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    4072064(0x3e2280) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    4072064(0x3e2280) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4072064(0x3e2280) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 3                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-26f6b21ec442090e               
  Marketing Name:          Radeon RX 7900 XT                  
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      81920(0x14000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2129                               
  BDFID:                   1024                               
  Internal Node ID:        2                                  
  Compute Unit:            84                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 550                                
  SDMA engine uCode::      19                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    20955136(0x13fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    20955136(0x13fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done *** 

### CPU

Intel

### Other software

_No response_

### LINKED ISSUE #3507: Switching dynamically between multiple LLM models on VRAM
### What are you trying to do?

At the moment, Ollama needs to load LLM one by one. It should be possible to have multiple LLM resident in VRAM memory and switch dynamically between the two.

### How should we solve this?

1. Check if the requested images can be loaded within the current hardware VRAM budget.
2. load multiple images in VRAM.
3. Augment API to switch dynamically between the two.  

### What is the impact of not solving this?

The present latency when loading and unloading multiple models.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dhiltgen**
This change adds support for multiple concurrent requests, as well as loading multiple models by spawning multiple runners.  This change is designed to be "opt in" initially, so the default behavior mimics the current sequential implementation (1 request at a time, and only a single model), but can be changed by setting environment variables for the server.  In the future we will adjust the default settings to enable concurrency by default.

By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via `OLLAMA_NUM_PARALLEL`.

By default, this change supports 1 loaded model at a time, which can be adjusted via `OLLAMA_MAX_LOADED_MODELS `.  Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity.  In the >1 scenario, we'll still perform VRAM prediction calculations to see if the new model will completely fit into available VRAM, but will prevent loading more than the specified number of runners even if they would have fit.  

This change also adjusts our GPU selection algorithm in multi-GPU scenarios.  If we can fit the model into a single GPU, we'll favor that over spreading it to multiple GPUs.

Note: system memory capacity is not taken into consideration in this change, so for CPU mode, setting max runners to zero could result in memory exhaustion and paging/swapping.

Fixes #2109
Fixes #1656
Fixes #1514
Fixes #3304 
Fixes #961 
Fixes #3507

### CODE REVIEW

**Comment by dillfrescott** [comment]
yes! I need this haha

**Comment by dillfrescott** [comment]
It needs to back off the vram usage a tiny bit. its so close to an OOM that an extended convo can cause a cuda error and crash ollama.

**Comment by G4Zz0L1** [comment]
Following this, seems just the thing I was trying to implement in other ways.
Let me know if I can be of help or for testing.
Thanks in advance!

**Comment by kimyanna** [comment]
Thanks for this PR @dhiltgen!

I'm testing this locally and it still executes the requests against `http://localhost:11434/api/generate` in sequence.

I built the binary, started the server and sent 4 parallel requests against `http://localhost:11434/api/generate` and they got queued up and executed one after the other. Can you share how to achieve concurrency with this PR?

Seems like a lot of people are waiting for this to be merged, well I couldn't wait :)

Thank you!

**Comment by metaspartan** [comment]
Tested this slightly, seems to work mostly via running multiple instances of ollama run, did not try via /api/generate endpoint though. One thing I noticed, which may be unrelated, is ollama models hanging at times or continuing in an infinite loop of output at times.

**Comment by alexander-potemkin** [comment]
I'm wondering - why not some kind of queue mechanism? I mean, sometimes response speed is not that crucial and the server's resources are limit - can't requests be queued somehow?

Just in case - I'm truly wondering why concurrency vs queuing; I understand if you choose not to respond, as you are clearly doing a heck of thing and my question is a bit of distraction, I would appreciate however the responce, if you have some time and thoughts to share!

**Comment by metaspartan** [comment]
> I'm wondering - why not some kind of queue mechanism? I mean, sometimes response speed is not that crucial and the server's resources are limit - can't requests be queued somehow?
> 
> Just in case - I'm truly wondering why concurrency vs queuing; I understand if you choose not to respond, as you are clearly doing a heck of thing and my question is a bit of distraction, I would appreciate however the responce, if you have some time and thoughts to share!

Efficiency, Responsiveness, Scalability; it makes Ollama scalable having concurrency vs. having to queue up sequential responses (which it does now). In the future you will want your AI Agents responding to multiple inputs in parallel rather than sequentially waiting, their is a lot of unused compute doing requests sequentially. Just my opinion, curious to hear dhiltgen's also.

**Comment by alexander-potemkin** [comment]
@metaspartan 

> Efficiency, Responsiveness, Scalability; it makes Ollama scalable having concurrency vs. having to queue up sequential responses (which it does now). In the future you will want your AI Agents responding to multiple inputs in parallel rather than sequentially waiting, their is a lot of unused compute doing requests sequentially. Just my opinion, curious to hear dhiltgen's also.

But how do you handle hitting hardware limits then?
It also doesn't feel like contradict one another - you could have, for example, 4 runners (f.ex: 3 CPU cores each) and queue - that shall be handled by the runners. Or not?


> queue up sequential responses (which it does now)

I was searching for ollama's queue mechanism, but didn't find anything on the topic - is there some reference or keywords I can search for, please?

**Comment by metaspartan** [comment]
> @metaspartan
> 
> > Efficiency, Responsiveness, Scalability; it makes Ollama scalable having concurrency vs. having to queue up sequential responses (which it does now). In the future you will want your AI Agents responding to multiple inputs in parallel rather than sequentially waiting, their is a lot of unused compute doing requests sequentially. Just my opinion, curious to hear dhiltgen's also.
> 
> But how do you handle hitting hardware limits then? It also doesn't feel like contradict one another - you could have, for example, 4 runners (f.ex: 3 CPU cores each) and queue - that shall be handled by the runners. Or not?

Yes, but then 4 runners could only handle 4 requests at a time (in queue), with this update, it would enable you to send >4 requests and it would process them in parallel.

> 
> > queue up sequential responses (which it does now)
> 
> I was searching for ollama's queue mechanism, but didn't find anything on the topic - is there some reference or keywords I can search for, please?

Since ollama uses llama.cpp this mainly makes use of the `--parallel` flag to enable parallelism, I believe it goes off slots for the runner queue usually, probably a question better aimed at @dhiltgen

**Comment by alexander-potemkin** [comment]
> Yes, but then 4 runners could only handle 4 requests at a time (in queue), with this update, it would enable you to send >4 requests and it would process them in parallel.

How can you handle more requests, than a hardware allows?

> Since ollama uses llama.cpp this mainly makes use of the --parallel flag to enable parallelism, I believe it goes off slots for the runner queue usually, probably a question better aimed at @dhiltgen

I guess we do need @dhiltgen , as I can't recall any queue mechanism on llama.cpp... 

Hence my confusion...

**Comment by metaspartan** [comment]
> > Yes, but then 4 runners could only handle 4 requests at a time (in queue), with this update, it would enable you to send >4 requests and it would process them in parallel.
> 
> How can you handle more requests, than a hardware allows?

Well if in queue, then each would be processed by itself, if in parallel, then you would take a hit performance wise especially if CPU only, this is more so useful for GPUs/Apple Silicon...

> 
> > Since ollama uses llama.cpp this mainly makes use of the --parallel flag to enable parallelism, I believe it goes off slots for the runner queue usually, probably a question better aimed at @dhiltgen
> 
> I guess we do need @dhiltgen , as I can't recall any queue mechanism on llama.cpp...
> 
> Hence my confusion...

They added the new flags back in September: https://github.com/ggerganov/llama.cpp/pull/3228

**Comment by dhiltgen** [comment]
I've updated the description above to better describe how this works.  There are 2 layers of concurrency introduced by this change.  One layer is leveraging the parallelism support in llama.cpp to process multiple concurrent requests against a single loaded model.  The other layer is starting multiple subprocesses to handle multiple models, up to the limits of VRAM capacity.

Once this merges, we'll be eager to have folks try out the multiple model loading by setting `OLLAMA_MAX_RUNNERS` to zero or a number greater than 1 and let us know if you hit any snags.

File: llm/memory.go [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+		"reallayers", opts.NumGPU,
+		"layers", layerCount,
+		"required", format.HumanBytes2(memoryRequiredTotal),
+		"used", format.HumanBytes2(memoryRequiredPartial),
+		"available", format.HumanBytes2(memoryAvailable),
+		"kv", format.HumanBytes2(kv),
+		"fulloffload", format.HumanBytes2(graphFullOffload),
+		"partialoffload", format.HumanBytes2(graphPartialOffload),
+	)
+	return layerCount, uint64(memoryMinimum)
```
Comment (mxyng) [inline llm/memory.go:119]: returning memoryMinimum is probably not what you want since it's being assigned to `estimatedVRAM`. `memoryRequiredPartial` is likely what you want

File: llm/memory.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+	}
+
+	if opts.NumCtx < 4 {
+		opts.NumCtx = 4
+	}
+
+	// Split up the GPUs by type and try them
+	for _, gpus := range allGpus.ByLibrary() {
+		layers, estimatedVRAM = PredictGPULayers(gpus, ggml, projectors, opts)
+		if layers >= int(ggml.KV().BlockCount()+1) || (opts.NumGPU > 0 && layers >= opts.NumGPU) {
```
Comment (mxyng) [inline llm/memory.go:28]: This seems like a brittle check since opts.NumGPU is changed by PredictGPULayers. Perhaps PredictGPULayers should return true/false if the model fits fully on the GPU?

File: llm/server.go [hunk 3]
```diff
@@ -34,24 +34,35 @@ type LlamaServer struct {
...
 
-var cpuOnlyFamilies = []string{
-	"mamba",
+	// TODO - this should be broken down by GPU
+	EstimatedVRAM uint64 // Estimated usage of VRAM by the loaded model
+
+	refMax   int // Maximum concurrent requests
+	refCount int
+	refMu    sync.Mutex
+	refCond  sync.Cond
```
Comment (mxyng) [inline llm/server.go:44]: [golang.org/x/sync/semaphore](https://pkg.go.dev/golang.org/x/sync/semaphore#) might be useful here

**Comment by alexander-potemkin** [comment]
> They added the new flags back in September: [ggerganov/llama.cpp#3228](https://github.com/ggerganov/llama.cpp/pull/3228)

I still can't see any kind of queue mechanism - quite the opposite, it feels like it's about parallel execution.

I'm looking for a way to use regular (or enhanced, with the same API) OpenAI SDK / client on a server that process requests in a queue, returning the results as they are ready - there are plenty of cases, when this approach is perfectly workable and much more cost-efficient.

**Comment by alexander-potemkin** [comment]
> Once this merges, we'll be eager to have folks try out the multiple model loading by setting `OLLAMA_MAX_RUNNERS` to zero or a number greater than 1 and let us know if you hit any snags.

@dhiltgen , thank you! I might be that guy, but I feel like I can't figure out use case.

From what I understand, if I set MAX_RUNNERS to zero - that means that I can only execute one model; with a number greater than 1 - means that I have multiple runners (given that I have enough CPU cores and/or GPU RAM).

And that feels like a completely different use cases... Could you please, help me to understand what I'm missing here?

**Comment by metaspartan** [comment]
> > They added the new flags back in September: [ggerganov/llama.cpp#3228](https://github.com/ggerganov/llama.cpp/pull/3228)
> 
> I still can't see any kind of queue mechanism - quite the opposite, it feels like it's about parallel execution.
> 
> I'm looking for a way to use regular (or enhanced, with the same API) OpenAI SDK / client on a server that process requests in a queue, returning the results as they are ready - there are plenty of cases, when this approach is perfectly workable and much more cost-efficient.

Because that is what this is about concurrency/parallelism with ollama. If you want to use it with regular queues just use the default settings or the current release?

**Comment by alexander-potemkin** [comment]
> Because that is what this is about concurrency/parallelism with ollama. If you want to use it with regular queues just use the default settings or the current release?

Does ollama provides any kind of queueing? I tried to find one, but failed...

**Comment by metaspartan** [comment]
> > Because that is what this is about concurrency/parallelism with ollama. If you want to use it with regular queues just use the default settings or the current release?
> 
> Does ollama provides any kind of queueing? I tried to find one, but failed...

It just does by default right now without this PR merged in. Any inference request currently with ollama API or commands will run them sequentially only, so you run #1 and then #2, #3, etc. #1 will finish first then it will proceed to do #2 inference then #3 etc.

**Comment by alexander-potemkin** [comment]
> It just does by default right now without this PR merged in. Any inference request currently with ollama API or commands will run them sequentially only, so you run 1 and then 2, 3, etc. 1 will finish first then it will proceed to do 2 inference then 3 etc.

Thank you. And where can I read about that and/or configure the queue? Expiration, queue length, etc?

File: llm/memory.go (hunk 1 above)
Comment (dhiltgen) [reply llm/memory.go:119]: total vram is what I'm trying to capture since I'm trying to completely fit models when allowing concurrency

File: llm/memory.go (hunk 2 above)
Comment (dhiltgen) [reply llm/memory.go:28]: Good catch.

**Comment by dhiltgen** [comment]
@alexander-potemkin we don't currently have any limits to the number of client connections.  I don't believe we have wired up any sort of expiration/timeout setting on the server side, although I haven't tested how long a client could theoretically be waiting.  The current code does not implement a formal queue mechanism to guarantee ordering for pending requests, it's based on locks and signaling, so it's random which waiting request would get unblocked when a prior request is completed.  I think adding a FIFO is something we could look at adding incrementally in the future.

**Comment by dhiltgen** [comment]
Slight correction to the above.  I just updated the implementation for concurrent requests to a single model to use a semaphore package that does FIFO for blocked requests so that gets us 1/2 way there.   The logic for multiple models that exceed VRAM capacity however still uses a regular mutex lock pattern thus it will be random which pending request gets loaded next.  Refining that to make it FIFO will be a nice incremental improvement.

**Comment by alexander-potemkin** [comment]
@dhiltgen , got it, makes perfect sense, thank you!

**Comment by dhiltgen** [comment]
Note for people following along.  I've adjusted the defaults so this PR now mimics current behavior of a single request at a time, and a single model at a time, but allows you to set env vars to opt-in to the new concurrency.

**Comment by artem-zinnatullin** [comment]
@dhiltgen outstanding work!

I've built Docker images from your branch `DOCKER_ORG=artem-zinnatullin BUILD_ARCH=amd64 scripts/build_docker.sh` (Bash scripts in ollama are really good!), ROCm image is published to GitHub Packages in case someone else wants to try it it: `ghcr.io/artem-zinnatullin/ollama:dhiltgen-concurrency-0.1.32-6-ge3573da-rocm`.

Here is a video of a successful test running 4 concurrent requests on two models: `llama2:13b` and `wizardlm2:7b` on my LLM server at home with AMD 7900 XTX (24GB VRAM) in Kubernetes

```js
# Just some test values, no particular meaning besides greater than 1.
export OLLAMA_NUM_PARALLEL=8
export OLLAMA_MAX_RUNNERS=6
```

https://github.com/ollama/ollama/assets/967132/ad364fa5-6cc0-4e28-8138-c03ca778afe2

This is crazy good!! 😻 

---

@dhiltgen If I may, I'd suggest you set up auto-publishing of Docker images to GitHub Packages or Docker Hub from your fork so the community could run more tests against this branch as it gets developed and make sure it's stable, happy to help you with this!

**Comment by artem-zinnatullin** [comment]
On a related note, I'm experiencing `CUDA error: out of memory` with 0.1.32-rocm (AMD GPU!) see #3693 where stock build just crashes on a medium size model like `mixtral:8x7b` (24.6GB) which worked fine on 0.1.31-rocm on same hardware (AMD GPU 7900 XTX 24GB VRAM)

On your branch however which is based on 0.1.32-rocm as of [last commit e3573da](https://github.com/ollama/ollama/pull/3418/commits/e3573da9b4a7a115b74ab034c26d196a3dbebf6a) I get some broken output instead of a `CUDA error: out of memory`:

image

Idk if that's something specific to your change or to the changes in `0.1.32-rocm`, but wanted to let you know!

File: llm/memory.go [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+		// disable partial offloading when model is greater than total system memory
+		opts.NumGPU = 0
+	} else if memoryAvailable > memoryRequiredTotal {
+		layerCount = int(ggml.KV().BlockCount()) + 1
+		memoryRequiredPartial = memoryRequiredTotal
+	}
+
+	var allLayers bool
+	if opts.NumGPU < 0 {
+		opts.NumGPU = layerCount
```
Comment (mxyng) [inline llm/memory.go:124]: opts is pass by value so this assignment is ineffective

File: llm/memory.go [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+		"reallayers", opts.NumGPU,
+		"layers", layerCount,
+		"required", format.HumanBytes2(memoryRequiredTotal),
+		"used", format.HumanBytes2(memoryRequiredPartial),
+		"available", format.HumanBytes2(memoryAvailable),
+		"kv", format.HumanBytes2(kv),
+		"fulloffload", format.HumanBytes2(graphFullOffload),
+		"partialoffload", format.HumanBytes2(graphPartialOffload),
+	)
+	return layerCount, uint64(memoryRequiredTotal), allLayers
```
Comment (mxyng) [inline llm/memory.go:141]: You probably don't need to return a 3-tuple. Returning layerCount and memory should be sufficient

Comment (mxyng) [inline llm/memory.go:141]: `memoryRequiredTotal` is likely not what you want. It represents the memory required to offload all layers. Instead, `memoryRequiredPartial` represents the memory required to offload `layerCount` layers. If `layerCount >= opts.NumGPU`, `memoryRequiredPartial` will be the same as `memoryRequiredTotal`

File: llm/memory.go (hunk 2 above)
Comment (mxyng) [reply llm/memory.go]: I realize now `PredictGPULayers` passes opts by value so this might be fine

File: llm/memory.go (hunk 4 above)
Comment (dhiltgen) [reply llm/memory.go:132]: Good catch.  I need to shift this out to server.go

**Comment by dhiltgen** [comment]
@artem-zinnatullin thanks for giving it a try!  We've been making minor fixes to the memory prediction on main, which I've been rebasing into this PR.  I've got a Windows test system with an RX 7900 XTX, and I just tried `mixtral:8x7b` with the latest code on this branch, and I'm able to get it to run.  It loads 30/33 layers.  Can you pull down the latest code from my fork and see if you still see it hitting OOM, or if it loads for you now too?

I'm hoping to merge this soon, so I'll hold off publishing binaries on my fork, but thanks for the suggestion.

**Comment by artem-zinnatullin** [comment]
Hey @dhiltgen! So, I rebuilt and published rocm image from last https://github.com/ollama/ollama/pull/3418/commits/8a981761baf3251a6d3e982144fd585c95364d0d commit `ghcr.io/artem-zinnatullin/ollama:dhiltgen-concurrency-8a98176-rocm`

Here is what I observe trying to run `mixtral:8x7b` on it with 7900 XTX:

- `mixtral:8x7b` is able to produce output 1 time, but then doesn't respond to consequent requests within the session
- ollama (serve) gets completely deadlocked after an freezing on `mixtral:8x7b` request that didn't produce output, stops responding over HTTP API to requests with other smaller models 
- Weirdly  ollama first almost fully loads VRAM with `mixtral:8x7b` but then clears VRAM completely while producing first successful output and never uses VRAM again


<details>

<summary>Here is full log:</summary>

```js
time=2024-04-18T20:58:00.143-06:00 level=INFO source=images.go:817 msg="total blobs: 51"
time=2024-04-18T20:58:00.143-06:00 level=INFO source=images.go:824 msg="total unused blobs removed: 0"
time=2024-04-18T20:58:00.143-06:00 level=INFO source=routes.go:1069 msg="Listening on [::]:11434 (version 0.1.32-17-g8a98176)"
time=2024-04-18T20:58:00.143-06:00 level=INFO source=payload.go:29 msg="extracting embedded files" dir=/tmp/ollama1344661343/runners
time=2024-04-18T20:58:01.702-06:00 level=INFO source=payload.go:42 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 cuda_v11 rocm_v60002]"
time=2024-04-18T20:58:01.702-06:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
time=2024-04-18T20:58:01.703-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-18T20:58:01.703-06:00 level=INFO source=amd_linux.go:46 msg="AMD Driver: 6.3.6"
time=2024-04-18T20:58:01.704-06:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=0 total="24560.0 MiB"
time=2024-04-18T20:58:01.704-06:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=0 available="24533.4 MiB"
time=2024-04-18T20:58:01.705-06:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=0 gpu_type=gfx1100
time=2024-04-18T20:58:53.849-06:00 level=INFO source=sched.go:268 msg="loaded runners" count=1
time=2024-04-18T20:58:53.849-06:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
time=2024-04-18T20:58:53.850-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-18T20:58:53.850-06:00 level=INFO source=amd_linux.go:46 msg="AMD Driver: 6.3.6"
time=2024-04-18T20:58:53.850-06:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=0 total="24560.0 MiB"
time=2024-04-18T20:58:53.850-06:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=0 available="24533.4 MiB"
time=2024-04-18T20:58:53.852-06:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=0 gpu_type=gfx1100
time=2024-04-18T20:58:53.852-06:00 level=INFO source=memory.go:123 msg="offload to gpu" layers.real=-1 layers.estimate=30 memory.available="24533.4 MiB" memory.required.full="25898.9 MiB" memory.required.partial="24235.9 MiB" memory.required.kv="128.0 MiB" memory.weights.total="25215.9 MiB" memory.weights.repeating="25043.0 MiB" memory.weights.nonrepeating="172.9 MiB" memory.graph.full="98.0 MiB" memory.graph.partial="181.0 MiB"
time=2024-04-18T20:58:53.853-06:00 level=INFO source=memory.go:123 msg="offload to gpu" layers.real=-1 layers.estimate=30 memory.available="24533.4 MiB" memory.required.full="25898.9 MiB" memory.required.partial="24235.9 MiB" memory.required.kv="128.0 MiB" memory.weights.total="25215.9 MiB" memory.weights.repeating="25043.0 MiB" memory.weights.nonrepeating="172.9 MiB" memory.graph.full="98.0 MiB" memory.graph.partial="181.0 MiB"
time=2024-04-18T20:58:53.854-06:00 level=INFO source=memory.go:123 msg="offload to gpu" layers.real=-1 layers.estimate=30 memory.available="24533.4 MiB" memory.required.full="25898.9 MiB" memory.required.partial="24235.9 MiB" memory.required.kv="128.0 MiB" memory.weights.total="25215.9 MiB" memory.weights.repeating="25043.0 MiB" memory.weights.nonrepeating="172.9 MiB" memory.graph.full="98.0 MiB" memory.graph.partial="181.0 MiB"
time=2024-04-18T20:58:53.854-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-18T20:58:53.854-06:00 level=INFO source=server.go:262 msg="starting llama server" cmd="/tmp/ollama1344661343/runners/rocm_v60002/ollama_llama_server --model /root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b --ctx-size 1024 --batch-size 512 --embedding --log-disable --n-gpu-layers 30 --parallel 8 --port 35297"
time=2024-04-18T20:58:53.854-06:00 level=INFO source=server.go:410 msg="waiting for llama runner to start responding"
{"function":"server_params_parse","level":"INFO","line":2603,"msg":"logging to file is disabled.","tid":"136457310547008","timestamp":1713495533}
{"build":2679,"commit":"7593639","function":"main","level":"INFO","line":2820,"msg":"build info","tid":"136457310547008","timestamp":1713495533}
{"function":"main","level":"INFO","line":2827,"msg":"system info","n_threads":12,"n_threads_batch":-1,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | ","tid":"136457310547008","timestamp":1713495533,"total_threads":24}
llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from /root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 2
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,58980]   = ["▁ t", "i n", "e r", "▁ a", "h e...
llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  21:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q4_0:  833 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8x7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 24.62 GiB (4.53 BPW)
llm_load_print_meta: general.name     = mistralai
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 ROCm devices:
  Device 0: Radeon RX 7900 XTX, compute capability 11.0, VMM: no
llm_load_tensors: ggml ctx size =    0.96 MiB
llm_load_tensors: offloading 30 repeating layers to GPU
llm_load_tensors: offloaded 30/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size = 23477.81 MiB
llm_load_tensors:  ROCm_Host buffer size =  1738.05 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 1024
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =   120.00 MiB
llama_kv_cache_init:  ROCm_Host KV buffer size =     8.00 MiB
llama_new_context_with_model: KV self size  =  128.00 MiB, K (f16):   64.00 MiB, V (f16):   64.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     1.10 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 826.00 MiB on device 0: cudaMalloc failed: out of memory
ggml_gallocr_reserve_n: failed to allocate ROCm0 buffer of size 866125824
llama_new_context_with_model: failed to allocate compute buffers
llama_init_from_gpt_params: error: failed to create context with model '/root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b'
{"function":"load_model","level":"ERR","line":410,"model":"/root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b","msg":"unable to load model","tid":"136457310547008","timestamp":1713495542}
time=2024-04-18T20:59:02.533-06:00 level=ERROR source=server.go:283 msg="error starting llama server" server=rocm_v60002 error="llama runner process no longer running: 1 error:failed to create context with model '/root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b'"
time=2024-04-18T20:59:02.534-06:00 level=INFO source=server.go:262 msg="starting llama server" cmd="/tmp/ollama1344661343/runners/cpu_avx2/ollama_llama_server --model /root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b --ctx-size 1024 --batch-size 512 --embedding --log-disable --n-gpu-layers 30 --parallel 8 --port 33887"
time=2024-04-18T20:59:02.534-06:00 level=INFO source=server.go:410 msg="waiting for llama runner to start responding"
{"function":"server_params_parse","level":"INFO","line":2603,"msg":"logging to file is disabled.","tid":"126279812892544","timestamp":1713495542}
{"function":"server_params_parse","level":"WARN","line":2380,"msg":"Not compiled with GPU offload support, --n-gpu-layers option will be ignored. See main README.md for information on enabling GPU BLAS support","n_gpu_layers":-1,"tid":"126279812892544","timestamp":1713495542}
{"build":2679,"commit":"7593639","function":"main","level":"INFO","line":2819,"msg":"build info","tid":"126279812892544","timestamp":1713495542}
{"function":"main","level":"INFO","line":2822,"msg":"system info","n_threads":12,"n_threads_batch":-1,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | ","tid":"126279812892544","timestamp":1713495542,"total_threads":24}
llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from /root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:                         llama.expert_count u32              = 8
llama_model_loader: - kv  10:                    llama.expert_used_count u32              = 2
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                          general.file_type u32              = 2
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,58980]   = ["▁ t", "i n", "e r", "▁ a", "h e...
llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  21:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:   32 tensors
llama_model_loader: - type q4_0:  833 tensors
llama_model_loader: - type q8_0:   64 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 8
llm_load_print_meta: n_expert_used    = 2
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8x7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 46.70 B
llm_load_print_meta: model size       = 24.62 GiB (4.53 BPW)
llm_load_print_meta: general.name     = mistralai
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.48 MiB
llm_load_tensors:        CPU buffer size = 25215.87 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 1024
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   128.00 MiB
llama_new_context_with_model: KV self size  =  128.00 MiB, K (f16):   64.00 MiB, V (f16):   64.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     1.10 MiB
llama_new_context_with_model:        CPU compute buffer size =   118.04 MiB
llama_new_context_with_model: graph nodes  = 1638
llama_new_context_with_model: graph splits = 1
{"function":"initialize","level":"INFO","line":448,"msg":"initializing slots","n_slots":8,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":0,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":1,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":2,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":3,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":4,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":5,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":6,"tid":"126279812892544","timestamp":1713495553}
{"function":"initialize","level":"INFO","line":457,"msg":"new slot","n_ctx_slot":128,"slot_id":7,"tid":"126279812892544","timestamp":1713495553}
{"function":"main","level":"INFO","line":3064,"msg":"model loaded","tid":"126279812892544","timestamp":1713495553}
{"function":"main","hostname":"127.0.0.1","level":"INFO","line":3267,"msg":"HTTP server listening","n_threads_http":"23","port":"33887","tid":"126279812892544","timestamp":1713495553}
{"function":"update_slots","level":"INFO","line":1578,"msg":"all slots are idle and system prompt is empty, clear the KV cache","tid":"126279812892544","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":0,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54918,"status":200,"tid":"126279439648512","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":1,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54920,"status":200,"tid":"126279448041216","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":2,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54930,"status":200,"tid":"126279456433920","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":5,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54950,"status":200,"tid":"126279498397440","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":3,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54944,"status":200,"tid":"126279506790144","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":4,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":54942,"status":200,"tid":"126279515182848","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":6,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":41264,"status":200,"tid":"126279490004736","timestamp":1713495553}
time=2024-04-18T20:59:13.417-06:00 level=INFO source=server.go:410 msg="waiting for llama runner to start responding"
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":7,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":41264,"status":200,"tid":"126279490004736","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":8,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":41264,"status":200,"tid":"126279490004736","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"POST","msg":"request","params":{},"path":"/tokenize","remote_addr":"127.0.0.1","remote_port":41264,"status":200,"tid":"126279490004736","timestamp":1713495553}
{"function":"process_single_task","level":"INFO","line":1506,"msg":"slot data","n_idle_slots":8,"n_processing_slots":0,"task_id":9,"tid":"126279812892544","timestamp":1713495553}
{"function":"log_server_request","level":"INFO","line":2734,"method":"GET","msg":"request","params":{},"path":"/health","remote_addr":"127.0.0.1","remote_port":41264,"status":200,"tid":"126279490004736","timestamp":1713495553}
{"function":"launch_slot_with_data","level":"INFO","line":830,"msg":"slot is processing task","slot_id":0,"task_id":10,"tid":"126279812892544","timestamp":1713495553}
{"function":"update_slots","ga_i":0,"level":"INFO","line":1809,"msg":"slot progression","n_past":0,"n_past_se":0,"n_prompt_tokens_processed":20,"slot_id":0,"task_id":10,"tid":"126279812892544","timestamp":1713495553}
{"function":"update_slots","level":"INFO","line":1836,"msg":"kv cache rm [p0, end)","p0":0,"slot_id":0,"task_id":10,"tid":"126279812892544","timestamp":1713495553}
{"function":"update_slots","level":"INFO","line":1601,"msg":"slot context shift","n_cache_tokens":128,"n_ctx":1024,"n_discard":63,"n_keep":1,"n_left":126,"n_past":127,"n_system_tokens":0,"slot_id":0,"task_id":10,"tid":"126279812892544","timestamp":1713495566}
{"function":"print_timings","level":"INFO","line":269,"msg":"prompt eval time     =     989.81 ms /    20 tokens (   49.49 ms per token,    20.21 tokens per second)","n_prompt_tokens_processed":20,"n_tokens_second":20.20587768776059,"slot_id":0,"t_prompt_processing":989.811,"t_token":49.49055,"task_id":10,"tid":"126279812892544","timestamp":1713495574}
{"function":"print_timings","level":"INFO","line":283,"msg":"generation eval time =   19590.05 ms /   169 runs   (  115.92 ms per token,     8.63 tokens per second)","n_decoded":169,"n_tokens_second":8.626828415445596,"slot_id":0,"t_token":115.91745562130177,"t_token_generation":19590.05,"task_id":10,"tid":"126279812892544","timestamp":1713495574}
{"function":"print_timings","level":"INFO","line":293,"msg":"          total time =   20579.86 ms","slot_id":0,"t_prompt_processing":989.811,"t_token_generation":19590.05,"t_total":20579.861,"task_id":10,"tid":"126279812892544","timestamp":1713495574}
{"function":"update_slots","level":"INFO","line":1640,"msg":"slot released","n_cache_tokens":126,"n_ctx":1024,"n_past":125,"n_system_tokens":0,"slot_id":0,"task_id":10,"tid":"126279812892544","timestamp":1713495574,"truncated":true}
{"function":"log_server_request","level":"INFO","line":2734,"method":"POST","msg":"request","params":{},"path":"/completion","remote_addr":"127.0.0.1","remote_port":41274,"status":200,"tid":"126279481612032","timestamp":1713495574}
[GIN] 2024/04/18 - 20:59:34 | 200 | 40.477191307s |     10.244.0.71 | POST     "/api/chat"
time=2024-04-18T20:59:35.327-06:00 level=INFO source=sched.go:161 msg="changing loaded model to update settings" model=/root/.ollama/models/blobs/sha256-e9e56e8bb5f0fcd4860675e6837a8f6a94e659f5fa7dce6a1076279336320f2b
time=2024-04-18T20:59:35.529-06:00 level=INFO source=gpu.go:96 msg="Detecting GPUs"
time=2024-04-18T20:59:35.535-06:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-18T20:59:35.535-06:00 level=INFO source=amd_linux.go:46 msg="AMD Driver: 6.3.6"
time=2024-04-18T20:59:35.535-06:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=0 total="24560.0 MiB"
time=2024-04-18T20:59:35.535-06:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=0 available="24533.4 MiB"
time=2024-04-18T20:59:35.540-06:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=0 gpu_type=gfx1100
```
</details>


Here is a video:


https://github.com/ollama/ollama/assets/967132/5bfe21bf-667b-43e0-a03d-03800075aba6

**Comment by fevolq** [comment]
I wonder if these contents have been merged into main, and whether the latest Docker image contains these functions? Thanks! 😊

File: docs/faq.md [hunk 6]
```diff
@@ -228,3 +228,11 @@ To unload the model and free up memory use:
...
 curl http://localhost:11434/api/generate -d '{"model": "llama2", "keep_alive": 0}'
 ```
+
+## How do I support more concurrent requests to the same model?
+
+By default Ollama currently supports 1 concurrent requests to a loaded model.  You can change this by setting `OLLAMA_NUM_PARALLEL` to a number greater than zero.
+
+## How do I load multiple different models at the same time?
+
+By default Ollama currently supports a single model at a time.  To enable multiple concurrent models, set `OLLAMA_MAX_RUNNERS`.  A value less than 1 will allow Ollama to load as many models as will fit in the available VRAM.  A value of 1 or greater will limit the number of models to no more than that value.
```
Comment (jmorganca) [inline docs/faq.md:238]: `OLLAMA_MAX_CONCURRENT_MODELS` or `OLLAMA_MAX_LOADED_MODELS` just to avoid exposing the inner workings?

File: gpu/gpu_info_cudart.c [hunk 7]
```diff
@@ -85,110 +81,95 @@ void cudart_init(char *cudart_lib_path, cudart_init_resp_t *resp) {
...
     }
-    ret = (*h.cudaMemGetInfo)(&memInfo.free, &memInfo.total);
-    if (ret != CUDART_SUCCESS) {
-      snprintf(buf, buflen, "cudart device memory info lookup failure %d", ret);
-      resp->err = strdup(buf);
-      return;
+    if (allNull != 0) {
+      snprintf(&resp->gpu_id[0], GPU_ID_LEN, "%d", i);
+    } else {
+      // GPU-d110a105-ac29-1d54-7b49-9c90440f215b
```
Comment (jmorganca) [inline gpu/gpu_info_cudart.c:134]: what is this uuid for?

File: llm/memory.go [hunk 8]
```diff
@@ -0,0 +1,164 @@
...
+				return true, estimatedVRAM
+			}
+		}
+	}
+	return false, estimatedVRAM
+}
+
+// Given a model and one or more GPU targets, predict how many layers and bytes we can load
+// The GPUs provided must all be the same Library
+func PredictGPULayers(gpus []gpu.GpuInfo, ggml *GGML, projectors []string, opts api.Options) (int, uint64) {
```
Comment (jmorganca) [inline llm/memory.go:44]:
```suggestion
func EstimateGPULayers(gpus []gpu.GpuInfo, ggml *GGML, projectors []string, opts api.Options) (int, uint64) {
```

nit: name

File: llm/server.go [hunk 9]
```diff
@@ -21,32 +21,57 @@ import (
...
+	"golang.org/x/sync/semaphore"
+
 	"github.com/ollama/ollama/api"
 	"github.com/ollama/ollama/format"
 	"github.com/ollama/ollama/gpu"
 )
 
-// LlamaServer is an instance of the llama.cpp server
-type LlamaServer struct {
+type LlamaServer interface {
```
Comment (jmorganca) [inline llm/server.go:31]: might be a silly question but why the re-introduction of an interface? for testing?

Comment (jmorganca) [reply llm/server.go:31]: disregard - saw the `mockLLM` further in the diff!

**Comment by DirtyKnightForVi** [comment]
> This change adds support for multiple concurrent requests, as well as loading multiple models by spawning multiple runners. This change is designed to be "opt in" initially, so the default behavior mimics the current sequential implementation (1 request at a time, and only a single model), but can be changed by setting environment variables for the server. In the future we will adjust the default settings to enable concurrency by default.
> 
> By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via `OLLAMA_NUM_PARALLEL`.
> 
> By default, this change supports 1 loaded model at a time, which can be adjusted via `OLLAMA_MAX_LOADED_MODELS `. Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity. In the >1 scenario, we'll still perform VRAM prediction calculations to see if the new model will completely fit into available VRAM, but will prevent loading more than the specified number of runners even if they would have fit.
> 
> This change also adjusts our GPU selection algorithm in multi-GPU scenarios. If we can fit the model into a single GPU, we'll favor that over spreading it to multiple GPUs.
> 
> Note: system memory capacity is not taken into consideration in this change, so for CPU mode, setting max runners to zero could result in memory exhaustion and paging/swapping.
> 
> Fixes #2109 Fixes #1656 Fixes #1514 Fixes #3304 Fixes #961 Fixes #3507

Has this change been merged into main now? Why didn't I see any difference when I tried using these two parameters in version v0.1.32?

**Comment by icsy7867** [comment]
> > This change adds support for multiple concurrent requests, as well as loading multiple models by spawning multiple runners. This change is designed to be "opt in" initially, so the default behavior mimics the current sequential implementation (1 request at a time, and only a single model), but can be changed by setting environment variables for the server. In the future we will adjust the default settings to enable concurrency by default.
> > By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via `OLLAMA_NUM_PARALLEL`.
> > By default, this change supports 1 loaded model at a time, which can be adjusted via `OLLAMA_MAX_LOADED_MODELS `. Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity. In the >1 scenario, we'll still perform VRAM prediction calculations to see if the new model will completely fit into available VRAM, but will prevent loading more than the specified number of runners even if they would have fit.
> > This change also adjusts our GPU selection algorithm in multi-GPU scenarios. If we can fit the model into a single GPU, we'll favor that over spreading it to multiple GPUs.
> > Note: system memory capacity is not taken into consideration in this change, so for CPU mode, setting max runners to zero could result in memory exhaustion and paging/swapping.
> > Fixes #2109 Fixes #1656 Fixes #1514 Fixes #3304 Fixes #961 Fixes #3507
> 
> Has this change been merged into main now? Why didn't I see any difference when I tried using these two parameters in version v0.1.32?

If you look at the pull request you are reading from, it is still open.  So it probably won't be merged until the PR is completed?

**Comment by DirtyKnightForVi** [comment]
> > > This change adds support for multiple concurrent requests, as well as loading multiple models by spawning multiple runners. This change is designed to be "opt in" initially, so the default behavior mimics the current sequential implementation (1 request at a time, and only a single model), but can be changed by setting environment variables for the server. In the future we will adjust the default settings to enable concurrency by default.
> > > By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via `OLLAMA_NUM_PARALLEL`.
> > > By default, this change supports 1 loaded model at a time, which can be adjusted via `OLLAMA_MAX_LOADED_MODELS `. Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity. In the >1 scenario, we'll still perform VRAM prediction calculations to see if the new model will completely fit into available VRAM, but will prevent loading more than the specified number of runners even if they would have fit.
> > > This change also adjusts our GPU selection algorithm in multi-GPU scenarios. If we can fit the model into a single GPU, we'll favor that over spreading it to multiple GPUs.
> > > Note: system memory capacity is not taken into consideration in this change, so for CPU mode, setting max runners to zero could result in memory exhaustion and paging/swapping.
> > > Fixes #2109 Fixes #1656 Fixes #1514 Fixes #3304 Fixes #961 Fixes #3507
> > 
> > 
> > Has this change been merged into main now? Why didn't I see any difference when I tried using these two parameters in version v0.1.32?
> 
> If you look at the pull request you are reading from, it is still open. So it probably won't be merged until the PR is completed?

"Thanks, just realized this because of my anxiety, I've been experimenting with multiple concurrent tasks in the intranet."

**Review by jmorganca — APPROVED** [review]

**Comment by erasmus74** [comment]
Hello!

This is an amazing PR. But I'm having trouble understanding the steps for this

`
By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via OLLAMA_NUM_PARALLEL.

By default, this change supports 1 loaded model at a time, which can be adjusted via OLLAMA_MAX_LOADED_MODELS . Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity. 
`

So to get my ollama to run the max models that fit in VRAM, do I need to adjust both OLLAMA_NUM_PARALLEL and OLLAMA_MAX_LOADED_MODELS? or do I just set OLLAMA_NUM_PARALLEL to 0 or do I set OLLAMA_MAX_LOADED_MODELS to 0?

And I'd suggest maybe updating a readme to reflect those instructions for clarity. Love the work done here, have been following daily

**Comment by dhiltgen** [comment]
> So to get my ollama to run the max models that fit in VRAM, do I need to adjust both OLLAMA_NUM_PARALLEL and OLLAMA_MAX_LOADED_MODELS? or do I just set OLLAMA_NUM_PARALLEL to 0 or do I set OLLAMA_MAX_LOADED_MODELS to 0?

There are 2 levels of concurrency which make this a little complicated.

OLLAMA_MAX_LOADED_MODELS controls how many models can be loaded at the same time.  You could set that to 3 and if 3 models fit in VRAM, we'd load 3, but attempting to load a 4th would block until one of the others is finished processing, even if it would have fit in VRAM.  If you didn't update OLLAMA_NUM_PARALLEL then each model could only handle 1 client request at a time (so 3 different clients could each talk to one of the loaded models at the same time in this example).

For OLLAMA_MAX_LOADED_MODELS, anything less than 1 wouldn't make sense (zero models?) so we map that to "unlimited" and just use the VRAM calculations. 

We'll probably hold off updating the README for the moment as this UX may change as folks test the feature and give feedback.  Ultimately we want to adjust the defaults so you never have to use these settings to get concurrent behavior.   You could start with `OLLAMA_MAX_LOADED_MODELS=0` and `OLLAMA_NUM_PARALLEL=4` as an initial setting and experiment with your GPUs and models and see how it performs.

Experiment and let us know how it goes.

**Comment by dhiltgen** [comment]
> Can we have control over which model is run on which GPU?

This is something we can look at adding incrementally as this feature matures. Feel free to file a new issue and capture how you'd like it to work.

**Comment by saul-jb** [comment]
I've just been testing this and it _feels_ buggy, it's a little hard for me to figure out what exactly is going on atm, so it is possible that it is just working as intended or I'm just not understanding how it is supposed to work.

I've set:
```
Environment="OLLAMA_MAX_LOADED_MODELS=9"
```

I am running 1 model normally over 2 GPU's and cannot seem to run more than 1 other model on the CPU (setting `num_gpu 0`) at the same time. They always queue up and complete one after another on the CPU while the model on the GPU runs at the same time.

I have plenty of ram and a few threads so I would like to test performance of have multiple models running CPU inference simultaneously.

I understand that the `OLLAMA_NUM_PARALLEL` just splits the context on a model already loaded in memory? Setting this to 9 allows my to run simultaneous prompts but memory usage is not going up, it is slower and the responses seem less accurate...

**Comment by erasmus74** [comment]
> I've just been testing this and it _feels_ buggy, it's a little hard for me to figure out what exactly is going on atm, so it is possible that it is just working as intended or I'm just not understanding how it is supposed to work.
> 
> I've set:
> 
> ```
> Environment="OLLAMA_MAX_LOADED_MODELS=9"
> ```
> 
> I am running 1 model normally over 2 GPU's and cannot seem to run more than 1 other model on the CPU (setting `num_gpu 0`) at the same time. They always queue up and complete one after another on the CPU while the model on the GPU runs at the same time.
> 
> I have plenty of ram and a few threads so I would like to test performance of have multiple models running CPU inference simultaneously.
> 
> I understand that the `OLLAMA_NUM_PARALLEL` just splits the context on a model already loaded in memory? Setting this to 9 allows my to run simultaneous prompts but memory usage is not going up, it is slower and the responses seem less accurate...

If I understand correctly, OLLAMA_NUM_PARALLEL is splitting num of calls you can make to a running LLM. so the mem usage isn't going up for that. So if you ran 1 model and made several calls to it, it would allow it as the whole model only needs to be loaded in memory once.

OLLAMA_MAX_LOADED_MODELS is what allows you to load up multiple models. So if you did a 2nd call to model A, it wouldn't need another loaded, but if Call B went to Model B, this setting would allow that model to load up in parallel for the call. Assuming its set to higher than 1.

The rest I believe is just backend logic to fill and manage space as needed for model memory. You're essentially changing the limits on the calls and the limits on num models loaded from 1 each to whatever you want.

**Comment by saul-jb** [comment]
> If I understand correctly, OLLAMA_NUM_PARALLEL is splitting num of calls you can make to a running LLM. so the mem usage isn't going up for that. So if you ran 1 model and made several calls to it, it would allow it as the whole model only needs to be loaded in memory once.
> 
> OLLAMA_MAX_LOADED_MODELS is what allows you to load up multiple models. So if you did a 2nd call to model A, it wouldn't need another loaded, but if Call B went to Model B, this setting would allow that model to load up in parallel for the call. Assuming its set to higher than 1.

Yes, that seems to be what I understand but it still doesn't explain why I cannot run multiple models on CPU with max loaded models set to a high value?

**Comment by dhiltgen** [comment]
@saul-jb the primary focus on the PR was GPU support. It looks like there's a slight logic flaw leading to the bug you pointed out where it only runs one model at a time in CPU mode.  I'll try to see if I can get a PR to fix that before we finalize 0.1.33

**Comment by dhiltgen** [comment]
CPU concurrency is fixed on main, and will be in the next RC for 0.1.33.

**Comment by saul-jb** [comment]
> CPU concurrency is fixed on main, and will be in the next RC for 0.1.33.

Thank you, appreciate the quick fix!

**Comment by DirtyKnightForVi** [comment]
> This change adds support for multiple concurrent requests, as well as loading multiple models by spawning multiple runners. This change is designed to be "opt in" initially, so the default behavior mimics the current sequential implementation (1 request at a time, and only a single model), but can be changed by setting environment variables for the server. In the future we will adjust the default settings to enable concurrency by default.
> 
> By default, this change supports 1 concurrent requests to a loaded model, which can be adjusted via `OLLAMA_NUM_PARALLEL`.
> 
> By default, this change supports 1 loaded model at a time, which can be adjusted via `OLLAMA_MAX_LOADED_MODELS `. Set to zero for fully dynamic based on VRAM capacity, or a fixed number greater than 1 to limit the total number of loaded models regardless of VRAM capacity. In the >1 scenario, we'll still perform VRAM prediction calculations to see if the new model will completely fit into available VRAM, but will prevent loading more than the specified number of runners even if they would have fit.
> 
> This change also adjusts our GPU selection algorithm in multi-GPU scenarios. If we can fit the model into a single GPU, we'll favor that over spreading it to multiple GPUs.
> 
> Note: system memory capacity is not taken into consideration in this change, so for CPU mode, setting max runners to zero could result in memory exhaustion and paging/swapping.
> 
> Fixes #2109 Fixes #1656 Fixes #1514 Fixes #3304 Fixes #961 Fixes #3507

I tested 0.1.33-rc5 and ran into a few issues. Here's what I found (I'm using A100*4, running ollama and open webUI, with seven models):
1. For models that can fit on a single card, ollama tends to load them individually onto one card.
2. When trying to launch different users on open webUI and simultaneously requesting the same model, it seems like there's a "load, then reload" queuing mechanism for processing these requests.
3. Building on issue 1, when attempting to load larger models, an error occurs: "Ollama: llama runner process no longer running: 1 error: failed to create context with model". It seems like there's insufficient memory.

**Comment by wwjCMP** [comment]
Can the latest version use multiple CPUs at the same time? My computer has two CPUs, but OLLAMA only utilizes one CPU during operation.

**Comment by kksasa** [comment]
It is nice feature but what I should do to let GPU efficiency get improved? Here I have one 48G GPU, but multi-user always uses about 9G only. 

Sounds like OLLAMA_NUM_PARALLEL is multi-threads on one model but not multi-process. Can I load more than one llama3 model to use more GPU ?

Below is my test data , 

---------------------
| 35%   55C    P8             20W /  300W |    **9764MiB** /  49140MiB |      8%      Default | **--> before load llama3**
| 30%   52C    P8             21W /  300W |   **18490MiB** /  49140MiB |      5%      Default | **--> after  load llama3**


ollama -v
ollama version is 0.1.38

->ollama serve
2024/05/24 10:55:38 routes.go:1008: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:4 
OLLAMA_NUM_PARALLEL:10 


*Run1
[GIN] 2024/05/24 - 11:03:57 | 200 |    7.6424075s |  1x.2xx.1xx.1xx | POST     "/api/chat"

*Run4
[GIN] 2024/05/24 - 11:04:40 | 200 |   10.1817673s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:04:41 | 200 |   10.9462723s | 1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:04:41 | 200 |   11.1079954s | 1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:04:41 | 200 |   11.2583423s |  1x.2xx.1xx.1xx | POST     "/api/chat"

*Run10
[GIN] 2024/05/24 - 11:05:25 | 200 |   24.6483192s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:26 | 200 |    24.800208s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:26 | 200 |   25.1671635s |  11x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   25.6961691s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   25.7053244s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   25.8505443s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   26.0904746s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   26.4191842s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:27 | 200 |   26.5223198s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:05:28 | 200 |    26.963918s |  1x.2xx.1xx.1xx | POST     "/api/chat"

*Run20
[GIN] 2024/05/24 - 11:06:32 | 200 |   22.5697177s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:35 | 200 |   26.1756319s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:36 | 200 |   26.4939432s |  11x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:36 | 200 |   26.6382723s |  11x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:36 | 200 |   27.3587459s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:37 | 200 |   27.7655412s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:39 | 200 |   29.4963508s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:39 | 200 |   30.3209045s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:40 | 200 |   31.0920823s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:43 | 200 |   33.9128137s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:06:58 | 200 |   49.3977018s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:02 | 200 |   53.2553835s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:03 | 200 |   54.3424822s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:04 | 200 |   54.6706669s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:05 | 200 |   55.4658572s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:06 | 200 |   56.7236671s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:06 | 200 |   56.8384949s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:07 | 200 |   57.5106068s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:08 | 200 |   58.3820639s |  1x.2xx.1xx.1xx | POST     "/api/chat"
[GIN] 2024/05/24 - 11:07:08 | 200 |   58.5070586s |  1x.2xx.1xx.1xx | POST     "/api/chat"

**Comment by dhiltgen** [comment]
> Can I load more than one llama3 model to use more GPU ?

This isn't currently supported, however you should be able to workaround it by creating slightly different models via a Modelfile.

**Comment by kksasa** [comment]
> > Can I load more than one llama3 model to use more GPU ?
> 
> This isn't currently supported, however you should be able to workaround it by creating slightly different models via a Modelfile.

yeah. I tried to load llama3 and mistral two models to let client side randomly choose llama or mistral which can mitigate llm response time to improve user experience. I did not find a good way to know how many llama3 or mistral are being used. So, each  time, client may send 7 llama3 and 3 mistral requests.

If possible ollama side provide one api to do the parallel model query ? 

I mean, there are 10 users access ollama server at the same time.  It expects 5 requests to llama and 5 to mistral to improve ollama  reponse time.  If ollama server side can give one API query the models using status that is greate to help client side choose which model should be called.
