### PR TITLE
mlx: fix imagegen lookup

### LINKED ISSUE #15533: Error: failed to initialize MLX: libmlxc.dylib not found
### What is the issue?

```shell
$ curl http://localhost:11434/api/generate -d '{
  "model": "x/z-image-turbo",
  "prompt": "a sunset over mountains",
  "width": 512,
  "height": 512,
  "steps": 4,
  "seed": 42,
  "stream": false
}'
{"error":"mlx runner failed: Error: failed to initialize MLX: libmlxc.dylib not found (exit: exit status 1)"}
```

### Relevant log output

```shell
time=2026-04-13T09:40:30.596+05:00 level=INFO source=sched.go:484 msg="system memory" total="48.0 GiB" free="31.0 GiB" free_swap="0 B"
time=2026-04-13T09:40:30.596+05:00 level=INFO source=sched.go:491 msg="gpu memory" id=0 library=Metal available="35.5 GiB" free="36.0 GiB" minimum="512.0 MiB" overhead="0 B"
time=2026-04-13T09:40:30.599+05:00 level=INFO source=server.go:171 msg="starting mlx runner subprocess" model=x/z-image-turbo:latest port=58548
time=2026-04-13T09:40:30.600+05:00 level=INFO source=sched.go:561 msg="loaded runners" count=1
time=2026-04-13T09:40:30.612+05:00 level=WARN source=server.go:164 msg=mlx-runner msg="time=2026-04-13T09:40:30.612+05:00 level=INFO msg=\"starting mlx runner\" model=x/z-image-turbo:latest port=58548 mode=imagegen"
time=2026-04-13T09:40:30.612+05:00 level=WARN source=server.go:164 msg=mlx-runner msg="time=2026-04-13T09:40:30.612+05:00 level=ERROR msg=\"unable to initialize MLX\" error=\"failed to initialize MLX: libmlxc.dylib not found\""
time=2026-04-13T09:40:30.612+05:00 level=WARN source=server.go:164 msg=mlx-runner msg="Error: failed to initialize MLX: libmlxc.dylib not found"
time=2026-04-13T09:40:30.612+05:00 level=ERROR source=sched.go:567 msg="error loading llama server" error="mlx runner failed: Error: failed to initialize MLX: libmlxc.dylib not found (exit: exit status 1)"
time=2026-04-13T09:40:30.613+05:00 level=INFO source=server.go:363 msg="stopping mlx runner subprocess" pid=40146
[GIN] 2026/04/13 - 09:40:30 | 500 |   97.157125ms |       127.0.0.1 | POST     "/api/generate"
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.20.6

### PR DESCRIPTION
**Pull request by dhiltgen**
Fixes #15533 - imagegen had fallen out of sync with the new layout for multiple mlx libraries on Metal.

### CODE REVIEW

File: x/imagegen/server.go [hunk 1]
```diff
@@ -200,6 +171,62 @@ func (s *Server) Ping(ctx context.Context) error {
...
+	}
+}
+
+func mlxLibraryPaths() []string {
+	if ml.LibOllamaPath == "" {
+		return nil
+	}
+
+	libraryPaths := []string{ml.LibOllamaPath}
+	if mlxDirs, err := filepath.Glob(filepath.Join(ml.LibOllamaPath, "mlx*")); err == nil {
```
Comment (pdevine) [inline x/imagegen/server.go]: Did you want this to look for the actual libs? Not a huge deal because I think adding extra paths _probably_ isn't going to hurt anything.

File: x/imagegen/server.go [hunk 2]
```diff
@@ -200,6 +171,62 @@ func (s *Server) Ping(ctx context.Context) error {
...
+	}
+	return libraryPaths
+}
+
+func configureMLXSubprocessEnv(cmd *exec.Cmd) {
+	libraryPaths := mlxLibraryPaths()
+	if len(libraryPaths) == 0 {
+		return
+	}
+
```
Comment (pdevine) [inline x/imagegen/server.go:189]: Maybe put in a comment with the order that it's going to check the various paths? This is a little hard to read right now.

**Review by pdevine — APPROVED** [review]
