### PR TITLE
fix: from blob

### LINKED ISSUE #3685: `FROM .` in Modelfile creates invalid model
### What is the issue?

When including `FROM .` in a Modelfile, an incorrect Modelfile will be generated if `.` elsewhere:

```
ollama show octopus --modelfile
# Modelfile generated by "ollama show"
# To build a new Modelfile based on this one, replace the FROM line with:
# FROM octopus:latest

FROM /Users/jmorgan/.ollama/models/blobs/sha256-33fdea506a5c3f5fde0112d8b8f50c4c009da49469c9bc2ffa973963e445f898
TEMPLATE """{{ @sha256:4e4d269e842069af0c07482684ed8779104f3ecf7cded7a1edd432a1bff54effSystem }}

Query: {{ @sha256:4e4d269e842069af0c07482684ed8779104f3ecf7cded7a1edd432a1bff54effPrompt }}

Response: {{ @sha256:4e4d269e842069af0c07482684ed8779104f3ecf7cded7a1edd432a1bff54effResponse }}"""
SYSTEM """Below is the query from the users, please call the correct function and generate the parameters to call the function@sha256:4e4d269e842069af0c07482684ed8779104f3ecf7cded7a1edd432a1bff54eff"""
```

### What did you expect to see?

_No response_

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### Architecture

_No response_

### Platform

_No response_

### Ollama version

_No response_

### GPU

_No response_

### GPU info

_No response_

### CPU

_No response_

### Other software

_No response_

### PR DESCRIPTION
**Pull request by mxyng**
from calls replace all which may affect other parts of the model file. instead, replace just the line.

resolves #3685

### CODE REVIEW

File: cmd/cmd.go [hunk 1]
```diff
@@ -220,14 +146,96 @@ func CreateHandler(cmd *cobra.Command, args []string) error {
...
-	request := api.CreateRequest{Name: args[0], Modelfile: string(modelfile), Quantization: quantization}
+	request := api.CreateRequest{Name: args[0], Modelfile: b.String(), Quantization: quantization}
 	if err := client.Create(cmd.Context(), &request, fn); err != nil {
 		return err
 	}
 
 	return nil
 }
 
+func tempZipFiles(path string) (string, error) {
```
Comment (mxyng) [inline cmd/cmd.go:157]: this is split from create handler since that function was getting too long

File: cmd/cmd.go [hunk 2]
```diff
@@ -95,106 +97,30 @@ func CreateHandler(cmd *cobra.Command, args []string) error {
 				return err
 			}
 
-			// TODO make this work w/ adapters
 			if fi.IsDir() {
-				tf, err := os.CreateTemp("", "ollama-tf")
-				if err != nil {
-					return err
-				}
-				defer os.RemoveAll(tf.Name())
```
Comment (BruceMacD) [inline cmd/cmd.go:104]: I see that this removal of the temp file is no longer done. I know that files in the temp dir will be cleaned up automatically, but could it still be nice to remove these files earlier due to their size?

File: parser/parser.go [hunk 3]
```diff
@@ -6,127 +6,185 @@ import (
...
-	for scanner.Scan() {
-		line := scanner.Bytes()
-
-		fields := bytes.SplitN(line, []byte(" "), 2)
-		if len(fields) == 0 || len(fields[0]) == 0 {
-			continue
+func Parse(r io.Reader) ([]Command, error) {
+	var cmds []Command
+	var errs []error
+	parseCommands(r)(func(cmd Command, err error) bool {
```
Comment (BruceMacD) [inline parser/parser.go:21]: I personally think it would be easier to read this if parseCommands just returned an array of errors, rather than yielding.

File: cmd/cmd.go (hunk 2 above)
Comment (mxyng) [reply cmd/cmd.go:104]: It's still there (line 107) but outside of tempZipFiles since removing it in that function negates all that hard work

File: parser/parser.go (hunk 3 above)
Comment (mxyng) [reply parser/parser.go]: Fair. Once `rangefunc` is enabled, this will look identical to the current implemention but unless the caller of Parse is updated, there's no real benefit.

File: parser/parser.go [hunk 4]
```diff
@@ -6,127 +6,168 @@ import (
...
+					return nil, err
+				}
 			}
-			if !slices.Contains([]string{"system", "user", "assistant"}, string(bytes.ToLower(fields[0]))) {
-				return nil, fmt.Errorf("role must be one of \"system\", \"user\", or \"assistant\"")
+		case stateMultiline:
+			if r == '"' && b.Len() == 0 {
+				quotes++
+			} else if r == '"' {
+				if quotes--; quotes == 0 {
```
Comment (pdevine) [inline parser/parser.go:91]: I find this syntax really weird. Does it only subtract one from quotes if it's equal and then do the other stuff? This would be much easier to read as `if quotes-1 == 0 { quotes-- }`

File: parser/parser.go [hunk 5]
```diff
@@ -6,127 +6,168 @@ import (
...
+					s = stateParameter
+				case "message":
+					s = stateMessage
+				default:
+					s = stateArgs
+				}
+			} else if newline(r) {
+				return nil, fmt.Errorf("missing value for [%s]", b.String())
+			} else {
+				return nil, fmt.Errorf("unexpected rune %q for state %d", r, s)
```
Comment (pdevine) [inline parser/parser.go:69]: This is going to trip up on comments which start with "# this is a comment". I think you'll need another state like `stateComment` which starts when you find a "#" at the beginning of the line and then ends when you get a newline.

File: parser/parser.go [hunk 6]
```diff
@@ -6,127 +6,168 @@ import (
...
+				if _, err := b.WriteRune(r); err != nil {
+					return nil, err
+				}
 			}
-			if !slices.Contains([]string{"system", "user", "assistant"}, string(bytes.ToLower(fields[0]))) {
-				return nil, fmt.Errorf("role must be one of \"system\", \"user\", or \"assistant\"")
+		case stateMultiline:
+			if r == '"' && b.Len() == 0 {
+				quotes++
+			} else if r == '"' {
```
Comment (pdevine) [inline parser/parser.go:90]: This will get tripped up on something like:

MESSAGE assistant """You are a "thing""""

I think you need to look for something like \" to allow the user to unescape double quotes after the first char. I can see this being a problem w/ the `/save` functionality in the REPL.

**Review by pdevine — COMMENTED** [review]
I like the new state machine for `parser.go`. Most comments are just nits, but the two things that worry me are:

1. not ignoring comments (this will bite me because half of my modelfiles have comments in them); and
2. we need to make sure the quotes stuff works... this is already a problem, and I think the change helps, but I can see this blowing up w/ `/save` right now if we don't escape/unescape quotes correctly.

File: parser/parser_test.go [hunk 7]
```diff
@@ -59,40 +66,212 @@ PARAMETER param1
...
+			commands, err := Parse(strings.NewReader(c.multiline))
+			assert.Equal(t, err, c.err)
+			assert.Truef(t, cmp.Equal(c.expected, commands, ignoreCommandBuffer), "expected %#v, got %#v", c.expected, commands)
+		})
+	}
 }
 
-func Test_Parser_Messages_BadRole(t *testing.T) {
+func TestParserParameters(t *testing.T) {
+	var cases = []string{
```
[the remark this answers is not in the document]
Comment (pdevine) [reply parser/parser_test.go:226]: Actually, I realized that won't matter because the parser doesn't actually check though.

File: parser/parser.go [hunk 8]
```diff
@@ -6,127 +6,168 @@ import (
...
+		} else if err != nil {
+			return nil, err
+		}
 
-	scanner := bufio.NewScanner(reader)
-	scanner.Buffer(make([]byte, 0, bufio.MaxScanTokenSize), bufio.MaxScanTokenSize)
-	scanner.Split(scanModelfile)
-	for scanner.Scan() {
-		line := scanner.Bytes()
+		if _, err := cmd.WriteRune(r); err != nil {
```
[the remark this answers is not in the document]
Comment (mxyng) [reply parser/parser.go:42]: it's to keep a raw buffer in addition to the parsed bytes. it's used regenerate the modelfile after parsing

File: parser/parser.go (hunk 5 above)
Comment (mxyng) [reply parser/parser.go:93]: I missed it since there wasn't any tests. should be fixed now

File: parser/parser.go (hunk 6 above)
Comment (mxyng) [reply parser/parser.go]: multiline is currently broken

**Review by pdevine — APPROVED** [review]
