### PR TITLE
Use stdin for term discovery on windows

### LINKED ISSUE #2698: Piping to `stdin` does not work in windows
Minor issue, but piping to stdin doesn't work on windows with git bash

```
$ cat README.md  | ollama run gemma "What is in this document?"
failed to get console mode for stdin: The handle is invalid.
```

### PR DESCRIPTION
**Pull request by dhiltgen**
When you feed input to the cmd via a pipe it no longer reports a warning

Before:
```
> echo "what is the captial of australia" | .\ollama.exe run phi
failed to get console mode for stdin: The handle is invalid.
 The capital of Australia is Canberra. It's located in the Australian Capital Territory, about 120 kilometers
northwest of Sydney and 130 kilometers southwest of Melbourne.
```

After fix:
```
> echo "what is the captial of australia" | .\ollama.exe run phi
 The capital city of Australia is Canberra. It is located in the Australian Capital Territory (ACT) and is home to important government buildings, such as Parliament House and the National Museum of Australia
```

Fixes #2698

### CODE REVIEW

File: cmd/cmd.go [hunk 1]
```diff
@@ -901,7 +901,7 @@ func NewCLI() *cobra.Command {
 
 	if runtime.GOOS == "windows" {
 		// Enable colorful ANSI escape code in Windows terminal (disabled by default)
```
Comment (BruceMacD) [inline cmd/cmd.go:903]: Is this comment about colorful ANSI escape codes still valid? I dont understand how this line was enabling this

Comment (dhiltgen) [reply cmd/cmd.go:903]: I can remove it - it was a community contribution.

Comment (dhiltgen) [reply cmd/cmd.go]: removed

**Review by BruceMacD — APPROVED** [review]
looks good once tests pass
