### PR TITLE
token repeat limit for prediction requests

### LINKED ISSUE #1910: "format": "json" in api request causes hang due to repeated tokens
When explicitly adding `"format": "json"` to an api request, the request then never seems to run to completion. In the logs I can see that the model is loaded, but apart from CPU usage to the maximum configured, nothing happens until I abort the request.

This hangs:
```shell
curl http://localhost:11434/api/generate -d '{ 
  "model": "mistral:latest",  
  "prompt": "Say hello.",
  "stream": false,
  "format": "json"
}'
```

This works just fine:
```shell
curl http://localhost:11434/api/generate -d '{ 
  "model": "mistral:latest",
  "prompt": "Say hello.",
  "stream": false
}'
```
The weird thing is, I did got some responses occasionally with `"format": "json"` present, but this example consistently fails.

I use the official Docker container. (Using rootless Podman). CPU only. Tested with 0.1.17, 0.1.18 and 0.1.19, on two different machines, one Intel, one AMD, both Kubuntu 23.10, with same results.

### PR DESCRIPTION
**Pull request by BruceMacD**
- abort prediction (generate/chat) requests when a token repeat limit is hit
- this prevent json format infinite loops
- this prevents a stuck request from starving the other queued requests
- move completion cancellation to its own function

Tested with this code from #1910 
```python
import requests 
import json
country = "france"
schema = {
	"city": {
		"type": "string",
		"description": "Name of the city"
	},
	"lat":{
		"type": "float",
		"description": "Decimal Latitude of the city"
	},
	"lon":{
		"type": "float",
		"description": "Decimal Longitude of the city"
	}
}
payload = {
	"model": "mistral-no-repeat",
	"messages": [
		{"role": "system", "content": f"You are a helpful AI assistant. The user will enter a country name and the assistant will return the decimal latitude and decimal longitude of the capital of the country. Output in JSON using the schema defined here: {schema}."},
		{"role": "user", "content": "japan"},
		{"role": "assistant", "content": "{\"city\": \"Tokyo\", \"lat\": 35.6748, \"lon\": 139.7624}"},
		{"role": "user", "content": country},
		],
		"format": "json",
		"stream": False
		
}
response = requests.post ("http://localhost:11434/api/chat", json=payload)
response.raise_for_status()
chat = response.json()
try:
    message_content_json = json.loads(chat['message']['content'])
    print(message_content_json)
except json.JSONDecodeError:
    print("JSONDecodeError: The content is not in proper JSON format.")
```

output is more reliable, with occasional JSON format failures which can be handled with a retry:
```bash
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', ' lat ': 48.8566, ' lon': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', 'lat': 48.8566, ' lon ': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', 'lat': 48.8566, ' lon ': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', ' lat': 48.8566, ' lon': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', 'lat': 48.8566, ' lon ': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', ' lat ': 48.8566, ' lon': 2.3522}
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
JSONDecodeError: The content is not in proper JSON format.
bruce@Bruces-MBP triage % poetry run python3 make_json_request.py
{'city': 'Paris', ' lat ': 48.8534, ' lon': 2.3522}
```

resolves #1910

### CODE REVIEW

File: llm/dyn_ext_server.go [hunk 1]
```diff
@@ -258,6 +255,20 @@ func (llm *dynExtServer) Predict(ctx context.Context, predict PredictOpts, fn fu
 					break out
 				}
 
+				switch {
+				case strings.TrimSpace(p.Content) == lastToken:
+					tokenRepeat++
+				default:
+					lastToken = strings.TrimSpace(p.Content)
```
Comment (mxyng) [inline llm/dyn_ext_server.go:262]: Should not trim space since <space>string and string are two separate tokens

File: llm/dyn_ext_server.go [hunk 2]
```diff
@@ -258,6 +255,20 @@ func (llm *dynExtServer) Predict(ctx context.Context, predict PredictOpts, fn fu
...
+					tokenRepeat = 0
+				}
+
+				// 30 picked as an arbitrary max token repeat limit, modify as needed
+				if tokenRepeat > 30 {
```
Comment (mxyng) [inline llm/dyn_ext_server.go:267]: This should be tunable maybe reuse `api.RepeatLastN`?

File: llm/dyn_ext_server.go (hunk 1 above)
Comment (BruceMacD) [reply llm/dyn_ext_server.go:262]: They are separate tokens, but for the sake of repetition they are the same. It is common for the LLM to output string tokens of differing lengths when stuck in a prediction loop. In that was we still should be able to handle it.

File: llm/dyn_ext_server.go (hunk 2 above)
Comment (BruceMacD) [reply llm/dyn_ext_server.go:267]: Hmm, this is a good suggestion but I'm hesitant to overload the setting with multiple functionalities.

File: llm/dyn_ext_server.go [hunk 3]
```diff
@@ -258,6 +255,20 @@ func (llm *dynExtServer) Predict(ctx context.Context, predict PredictOpts, fn fu
 					break out
 				}
 
+				switch {
```
Comment (jmorganca) [inline llm/dyn_ext_server.go:258]: not: if-else might be a bit easier to read

**Review by jmorganca — APPROVED** [review]
