### PR TITLE
fix: chat system prompting overrides

### LINKED ISSUE #2492: System Prompt not honored until re-run `ollama serve`
There are actually two issues regarding System Prompt in the current main branch, and I believe them to be related.

# Issue 1: `SYSTEM` prompt in modelfile not honored
If I run a model, then create a new one based the same model, but with a new `SYSTEM` prompt, the new `SYSTEM` prompt is not honored. Killing the current ollama serve process and re-runing a new one with `ollama serve` would solve the problem.

### How to replicate
Start a new server by `ollama serve` with `OLLAMA_DEBUG=1`
Run client with any model, for example, `ollama run phi`
Input a user prompt, you will find prompt debug info on server side, like
```
time=2024-02-14T06:55:05.081-05:00 level=DEBUG source=routes.go:1205 msg="chat handler" prompt="System: A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful answers to the user's questions.\nUser: hello\nAssistant:" images=0
```
Quit the client, create a custom modelfile like
```
FROM phi
SYSTEM """I want you to speak French only."""
```
Create/run a new model with the custom modelfile
Input a user prompt, check prompt debug info on server side again, you will find that prompt debug info has the same System prompt as before. It is not updated to the custom system prompt specified in the modelfile.

If I restart server, and re-run the client with same custom model, then the prompt debug info in the server side is updated correctly.

# Issue 2: `/set system` command in CLI changes System Prompt incorrectly
If I load a model, then use `/set system` to change System Prompt, ollama will actually append this new system prompt to the existing one, instead of replacing them.

### How to replicate
Start a new server by `ollama serve` with `OLLAMA_DEBUG=1`
Run client with any model, for example, `ollama run phi`
Set a new system prompt in CLI, like
```
/set system I want you to speak French only.
```
You can confirm that the system prompt has indeed been changed by command `/show modelfile` or `/show system`
Input a user prompt, you will find prompt debug info on server side looks like:
```
time=2024-02-14T07:13:40.139-05:00 level=DEBUG source=routes.go:1205 msg="chat handler" prompt="System: A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful answers to the user's questions.\nUser: \nAssistant:System: I want you to speak French only.\nUser: hello\nAssistant:" images=0
```
You can see the original system prompt is still there and the new system prompt is appended, followed by user input.

Furthermore, to make it worse, every time I set a new system prompt with `/set system`, the new system prompt will be appended to the old ones, instead of replacing them.

### PR DESCRIPTION
**Pull request by BruceMacD**
This change fixes two more system message related issues with the CLI and message templates.
- When `/set system ...` is run multiple times in the CLI, use only the most recent system message rather than adding multiple system messages to the history.
- Do not add the model's default message as a first message when a new system message is specified.
- When a request was made to a model than inherits from the currently loaded model the system and template were not updated in the /chat endpoint. The fix is to use the requested model rather than the loaded one.

Previous behavior, when running a model and setting a new system message:
```
ollama run phi
>>> /set system you are mario
Set system message.
>>> hi
```
```
level=DEBUG source=routes.go:1205 msg="chat handler" prompt="System: A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful answers to the user's questions.\nUser: \nAssistant:System: you are mario\nUser: hi\nAssistant:"
```

New behavior:
```
level=DEBUG source=routes.go:1205 msg="chat handler" prompt="System: you are mario\nUser: hi\nAssistant:"
```

resolves #2492 

Follow up: This keep the "system message history" further testing on model behavior of this is needed, it could be better to just override the system message, and not keep the old system message in the history.

### CODE REVIEW

File: server/prompt.go [hunk 1]
```diff
@@ -114,7 +115,7 @@ func ChatPrompt(tmpl string, system string, messages []api.Message, window int,
 	for _, msg := range messages {
 		switch strings.ToLower(msg.Role) {
 		case "system":
-			if p.System != "" || p.Prompt != "" || p.Response != "" {
+			if !p.first && (p.System != "" || p.Prompt != "" || p.Response != "") {
```
Comment (jmorganca) [inline server/prompt.go:118]: Let's check `len(p)` instead?

Comment (jmorganca) [reply server/prompt.go:118]: I think we also need to check that it's equivalent to the provided system prompt `system`, since this will cause an issue with:

```
[{
  "role": "user",
  "message": "hello!"
}, {
  "role": "system",
  "message": "you are a happy panda"
}]
```

File: server/prompt.go [hunk 2]
```diff
@@ -97,11 +97,12 @@ func ChatPrompt(tmpl string, system string, messages []api.Message, window int,
...
+		first  bool
 		images []int
 		tokens int
 	}
 
-	var p prompt
+	p := prompt{first: true}
 
 	// Set the first system prompt to the model's system prompt
 	if system != "" {
```
Comment (jmorganca) [inline server/prompt.go:108]: An alternative to below is to prepend a system message, which might make things a bit easier to reason about here. This could actually happen out of `ChatPrompt` and instead happen in `ChatHandler`

```
if len(messages) == 0 {
  return "", nil
}

// prepend the model system message if required
if messages[0].Role != "system" {
  messages = append({Role: "system", "Content": system}, messages...)
}

var p prompt
```

File: server/routes.go [hunk 3]
```diff
@@ -1167,7 +1167,17 @@ func ChatHandler(c *gin.Context) {
 
 	checkpointLoaded := time.Now()
 
-	prompt, err := chatPrompt(c.Request.Context(), req.Messages)
+	if len(req.Messages) > 0 && req.Messages[0].Role != "system" {
+		// if the first message is not a system message, then add the model's default system message
```
Comment (jmorganca) [inline server/routes.go:1171]: nit: move this above the `if`

File: server/routes.go [hunk 4]
```diff
@@ -1092,12 +1092,12 @@ func streamResponse(c *gin.Context, ch chan any) {
...
 
 // ChatPrompt builds up a prompt from a series of messages for the currently `loaded` model
-func chatPrompt(ctx context.Context, messages []api.Message) (string, error) {
+func chatPrompt(ctx context.Context, template string, messages []api.Message, numCtx int) (string, error) {
 	encode := func(s string) ([]int, error) {
 		return loaded.runner.Encode(ctx, s)
 	}
 
-	prompt, err := ChatPrompt(loaded.Model.Template, loaded.Model.System, messages, loaded.Options.NumCtx, encode)
+	prompt, err := ChatPrompt(template, messages, numCtx, encode)
```
Comment (jmorganca) [inline server/routes.go:1100]: much cleaner

File: cmd/interactive.go [hunk 5]
```diff
@@ -180,6 +180,7 @@ func generateInteractive(cmd *cobra.Command, opts runOptions) error {
 
 	var sb strings.Builder
 	var multiline MultilineState
+	var system string
```
Comment (jmorganca) [inline cmd/interactive.go:183]: nit: would be great to avoid the extra state here

**Review by jmorganca — APPROVED** [review]
looks good, thanks for fixing. A few minor nit comments that would be great to address

File: cmd/interactive.go [hunk 6]
```diff
@@ -354,8 +354,16 @@ func generateInteractive(cmd *cobra.Command, opts runOptions) error {
...
-						opts.System = sb.String()
-						opts.Messages = append(opts.Messages, api.Message{Role: "system", Content: opts.System})
+						opts.System = sb.String() // for display in modelfile
+						newMessage := api.Message{Role: "system", Content: sb.String()}
+						// Check if the slice is not empty and the last message is from 'system'
+						if len(opts.Messages) > 0 && opts.Messages[len(opts.Messages)-1].Role == "system" {
+							// Replace the last message
+							opts.Messages[len(opts.Messages)-1] = newMessage
+						} else {
+							// Append the new message
```
Comment (BruceMacD) [inline cmd/interactive.go:364]:
```suggestion
```

**Comment by nodelike** [comment]
How do I get this changes in my Mac and Windows? Should I manual build, or will there be an OTA update?

**Comment by nodelike** [comment]
@BruceMacD @jmorganca  How do I get this changes in my Mac and Windows? Should I manual build, or will there be an OTA update?
