### PR TITLE
fix: noprune on pull

### LINKED ISSUE #6333: "couldn't remove unused layers: invalid character '\x00' looking for beginning of value"
### What is the issue?

image

```
(base) ollama % ollama pull llama3.1:8b-instruct-q8_0
pulling manifest 
pulling cc04e85e1f86... 100% ▕█████████████████████████████████████▏ 8.5 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling 4a4a958ae550... 100% ▕█████████████████████████████████████▏  485 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
(base) ollama % ollama pull llama3.1:70b-instruct-q5_K_M
pulling manifest 
pulling f8f84c9d6421... 100% ▕█████████████████████████████████████▏  49 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling a9528db392c2... 100% ▕█████████████████████████████████████▏  488 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
(base) ollama % ollama pull llama3.1:70b-instruct-q4_K_M
pulling manifest 
pulling de20d2cf2dc4... 100% ▕█████████████████████████████████████▏  42 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling 4bde18c49e43... 100% ▕█████████████████████████████████████▏  488 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
couldn't remove unused layers: invalid character '\x00' looking for beginning of value 
success 
(base) ollama % ollama pull llama3.1:70b-instruct-q4_K_M
pulling manifest 
pulling de20d2cf2dc4... 100% ▕█████████████████████████████████████▏  42 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling 4bde18c49e43... 100% ▕█████████████████████████████████████▏  488 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
couldn't remove unused layers: invalid character '\x00' looking for beginning of value 
success 
(base) ollama % ollama pull llama3.1:70b-instruct-q5_K_M
pulling manifest 
pulling f8f84c9d6421... 100% ▕█████████████████████████████████████▏  49 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling a9528db392c2... 100% ▕█████████████████████████████████████▏  488 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
couldn't remove unused layers: invalid character '\x00' looking for beginning of value 
success 
(base) ollama % ollama pull llama3.1:8b-instruct-q8_0   
pulling manifest 
pulling cc04e85e1f86... 100% ▕█████████████████████████████████████▏ 8.5 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling 4a4a958ae550... 100% ▕█████████████████████████████████████▏  485 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
couldn't remove unused layers: invalid character '\x00' looking for beginning of value 
success 
(base) ollama % ollama pull llama3.1:8b-instruct-fp16   
pulling manifest 
pulling 09cd6813dc2e... 100% ▕█████████████████████████████████████▏  16 GB                         
pulling 11ce4ee3e170... 100% ▕█████████████████████████████████████▏ 1.7 KB                         
pulling 0ba8f0e314b4... 100% ▕█████████████████████████████████████▏  12 KB                         
pulling 56bb8bd477a5... 100% ▕█████████████████████████████████████▏   96 B                         
pulling daa7d15f6d0b... 100% ▕█████████████████████████████████████▏  484 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
couldn't remove unused layers: invalid character '\x00' looking for beginning of value 
success 
(base) ollama % 
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.3.5-1-gb807ec8

### PR DESCRIPTION
**Pull request by mxyng**
`OLLAMA_NOPRUNE` is ignored on pull requests. switch to `envconfig.NoPrune()`; `noprune` was check but never set

ignore any manifest that's not actually a manifest. this can be files such as `.DS_Store` on macOS

resolves #6333

### CODE REVIEW

File: server/images.go [hunk 1]
```diff
@@ -687,43 +687,18 @@ func CopyModel(src, dst model.Name) error {
 	return err
 }
 
-func deleteUnusedLayers(skipModelPath *ModelPath, deleteMap map[string]struct{}) error {
-	fp, err := GetManifestPath()
+func deleteUnusedLayers(deleteMap map[string]struct{}) error {
+	manifests, err := Manifests()
```
Comment (jessegross) [inline server/images.go:691]: This is a nice code reduction to use the Manifests function. However, did you want to only skip errors for invalid JSON? This will also ignore errors like file permission denied, etc.

Comment (mxyng) [reply server/images.go:691]: You're right. I missed that

**Review by jessegross — APPROVED** [review]
