### PR TITLE
Return Correct Prompt Eval Count Regardless of Cache Prompt

### LINKED ISSUE #2068: `prompt_eval_count` disappears after repeated requests with same prompt
I noticed some odd behaviour when working with ollama (via litellm as I have been trying to fix a bug in the integration over there). 

The `prompt_eval_count` parameter disappears from the response on a repeated request, yet the `prompt_eval_duration` (and other metrics) are still in the response payload. This happens for `stream: true` and `stream: false` variants across multiple models.

For example, a basic request like this run twice in a row:
```
 curl -X POST http://0.0.0.0:11434/api/chat -d '{"model": "orca2", "messages": [{"role": "user", "content": "What is your purpose?"}], "stream": false}'
```

First response:
```json
{"model":"orca2","created_at":"2024-01-19T00:01:42.266089Z","message":{"role":"assistant","content":"My purpose is to assist you with any information or tasks you need, using my knowledge and skills. I am an AI assistant created by Microsoft. Is there something I can help you with?"},"done":true,"total_duration":876557125,"load_duration":725667,"prompt_eval_count":11,"prompt_eval_duration":275489000,"eval_count":39,"eval_duration":595078000}
```

Subsequent responses:
```json
{"model":"orca2","created_at":"2024-01-19T00:05:12.20112Z","message":{"role":"assistant","content":"Possible responses:\n\n- My purpose is to assist users with their questions and tasks, using natural language processing and artificial intelligence.\n- I don't have a fixed purpose, but I try to help you find information and solve problems that you ask me.\n- My purpose is to learn from you and improve my skills and knowledge by interacting with you."},"done":true,"total_duration":1384266083,"load_duration":2776833,"prompt_eval_duration":215464000,"eval_count":75,"eval_duration":1163950000}
```

Is this an intentional omission on any subsequent responses with the same prompt, or a bug?

### LINKED ISSUE #5370: OpenAI Chat Compatibility Incorrect Prompt Eval
### What is the issue?

ollama returns 0 for prompt eval if the prompt was cached, but openai returns the actual count. prompt_tokens = 0 in the usage struct in the response.

### OS

_No response_

### GPU

_No response_

### CPU

_No response_

### Ollama version

_No response_

### PR DESCRIPTION
**Pull request by royjhan**
Resolves #5370 
Resolves #2068 
Resolves https://github.com/ollama/ollama-js/issues/66

### CODE REVIEW

File: api/types.go [hunk 1]
```diff
@@ -94,11 +94,14 @@ type ChatRequest struct {
...
 
 	// KeepAlive controls how long the model will stay loaded into memory
-	// followin the request.
+	// following the request.
 	KeepAlive *Duration `json:"keep_alive,omitempty"`
 
 	// Options lists model-specific options.
 	Options map[string]interface{} `json:"options"`
+
+	// OpenAI indicates redirection from the compatibility endpoint.
```
Comment (jmorganca) [inline api/types.go:103]: Adding this flag isn't quite right. Instead, let's fix this in all of the `/api/generate`, `/api/chat` and `/v1/chat/completions` endpoints in one PR as it is broken in all three.

Caching is an implementation detail and shouldn't affect these fields in our API (it does today):

* `prompt_eval_count`
* `eval_count`

**Review by jmorganca — APPROVED** [review]
Thanks for fixing
