### PR TITLE
Fix absolute path names + gguf detection

### LINKED ISSUE #8427: 0.5.5 Model Creation on Windows Seems Broken
### What is the issue?

Version 0.5.5 seems to have broken create functionality on Windows. I use a PowerShell script to create new models with different templates. The first step in the script is to run
`  ollama create  '<model name>'  -f  <full path to model file>`

The model file is a one line file
`  FROM <full path to GGUF>`

With 0.5.5 it errors on model creation as it mangles the file path (seems to pre-pend the OLLAMA_MODELS environment variable to the GGUF path). When I modify the model file to take this into account and run
`  ollama create 'testmodel1' -f <full path to model file>`
directly I get an 'Invalid model name' error.

Rolling back to 0.5.4 resolves the issue.

I'm using the Ollama setup installer.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.5.5

### PR DESCRIPTION
**Pull request by pdevine**
This change fixes two issues with the model creation:

1. Absolute pathnames for GGUF files were being treated as a relative pathname; and
2. The GGUF image detection wasn't able to correctly determine if a GGUF file w/o the correct extension was actually a GGUF file.

This change fixes both issues and adds additional unit tests.

Fixes #8427 and #8423

### CODE REVIEW

File: parser/parser.go [hunk 1]
```diff
@@ -591,6 +591,8 @@ func expandPathImpl(path, relativeDir string, currentUserFunc func() (*user.User
 		}
 
 		path = filepath.Join(homeDir, path)
+	} else if filepath.IsAbs(path) {
```
Comment (jmorganca) [inline parser/parser.go:594]: nit: would it be better to short circuit this at the top of the function?

File: server/create.go [hunk 2]
```diff
@@ -178,12 +178,35 @@ func convertModelFromFiles(files map[string]string, baseLayers []*layerGGML, isA
...
-		} else if strings.HasSuffix(fn, ".bin") || strings.HasSuffix(fn, ".gguf") {
+		} else if strings.HasSuffix(fn, ".gguf") {
 			return "gguf"
+		} else {
+			// try to see if we can find a gguf file even without the file extension
+			blobPath, err := GetBlobsPath(files[fn])
+			if err != nil {
+				slog.Error("error gettings blobs path")
+				return ""
+			}
```
Comment (jmorganca) [inline server/create.go:192]:
```suggestion
			}
			defer f.Close()
```

File: server/create.go [hunk 3]
```diff
@@ -178,12 +178,35 @@ func convertModelFromFiles(files map[string]string, baseLayers []*layerGGML, isA
...
+			buf := make([]byte, 4)
+			_, err = f.Read(buf)
+			if err != nil {
+				slog.Error("error reading file", "error", err)
+				return ""
+			}
+
+			ct := llm.DetectGGMLType(buf)
```
Comment (jmorganca) [inline server/create.go:206]: Will this handle files with size less than 4 bytes?

File: server/create.go [hunk 4]
```diff
@@ -178,12 +178,35 @@ func convertModelFromFiles(files map[string]string, baseLayers []*layerGGML, isA
...
 		if strings.HasSuffix(fn, ".safetensors") {
 			return "safetensors"
-		} else if strings.HasSuffix(fn, ".bin") || strings.HasSuffix(fn, ".gguf") {
+		} else if strings.HasSuffix(fn, ".gguf") {
 			return "gguf"
+		} else {
+			// try to see if we can find a gguf file even without the file extension
+			blobPath, err := GetBlobsPath(files[fn])
+			if err != nil {
+				slog.Error("error gettings blobs path")
```
Comment (jmorganca) [inline server/create.go:190]: Should we print the error here? 
```suggestion
				slog.Error("failed to get blobs path", "error", err)
```

File: server/create.go (hunk 2 above)
Comment (pdevine) [reply server/create.go:192]: Good catch.

File: server/create.go (hunk 3 above)
Comment (pdevine) [reply server/create.go:208]: Yeah. The buffer will just be smaller. I added a test for this though.

File: server/create.go (hunk 4 above)
Comment (pdevine) [reply server/create.go]: I think so. If the digest is invalid that's definitely an error.

**Review by jmorganca — APPROVED** [review]
