### PR TITLE
Centralize GPU configuration vars

### LINKED ISSUE #4139: only 1 GPU found -- regression 1.32 -> 1.33
### What is the issue?

Hi everyone,

Sorry I don't have much time to write much; but going from 1.32 to 1.33, this:

```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   yes
ggml_cuda_init: CUDA_USE_TENSOR_CORES: no
ggml_cuda_init: found 3 CUDA devices:
  Device 0: Tesla V100S-PCIE-32GB, compute capability 7.0, VMM: yes
  Device 1: Tesla V100S-PCIE-32GB, compute capability 7.0, VMM: yes
  Device 2: Tesla V100S-PCIE-32GB, compute capability 7.0, VMM: yes
llm_load_tensors: ggml ctx size =    0.45 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    70.31 MiB
llm_load_tensors:      CUDA0 buffer size =  1194.53 MiB
llm_load_tensors:      CUDA1 buffer size =  1194.53 MiB
llm_load_tensors:      CUDA2 buffer size =  1188.49 MiB
```

changed into this:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   yes
ggml_cuda_init: CUDA_USE_TENSOR_CORES: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Tesla V100S-PCIE-32GB, compute capability 7.0, VMM: yes
llm_load_tensors: ggml ctx size =    0.30 MiB
llm_load_tensors: offloading 3 repeating layers to GPU
llm_load_tensors: offloaded 3/33 layers to GPU
llm_load_tensors:        CPU buffer size =  3647.87 MiB
llm_load_tensors:      CUDA0 buffer size =   325.78 MiB
```

1.33 hammers my CPU cores, is generally slower and doesn't even utilize the one GPU it *does* find properly.

I need the new concurrency features, so I'd really appreciate it if 1.33 worked on my machine.

Please help.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

1.33

### PR DESCRIPTION
**Pull request by dhiltgen**
This should aid in troubleshooting by capturing and reporting the GPU settings at startup in the logs along with all the other server settings.

Fixes #4139 

Example output setting the ROCm gfx override:
```
2024/05/08 19:33:27 routes.go:993: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:10.3.0 OLLAMA_DEBUG:true OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:1 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:*] OLLAMA_RUNNERS_DIR: OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
```

### CODE REVIEW

**Review by jmorganca — APPROVED** [review]

File: server/envconfig/config.go [hunk 1]
```diff
@@ -163,12 +182,19 @@ func LoadConfig() {
...
+	if onp := clean("OLLAMA_MAX_QUEUE"); onp != "" {
 		p, err := strconv.Atoi(onp)
 		if err != nil || p <= 0 {
 			slog.Error("invalid setting", "OLLAMA_MAX_QUEUE", onp, "error", err)
 		} else {
 			MaxQueuedRequests = p
 		}
 	}
+
+	CudaVisibleDevices = clean("CUDA_VISIBLE_DEVICES")
```
Comment (dims) [inline server/envconfig/config.go:194]: @dhiltgen is this public variable `CudaVisibleDevices` meant to be used in `cudaGetVisibleDevicesEnv`?
https://github.com/ollama/ollama/blob/ee49844d09c5ee76a258ac53971e37bbf7857400/gpu/cuda_common.go#L10

Comment (dhiltgen) [reply server/envconfig/config.go:194]: Good question.  

For NVIDIA GPUs, we use their C libraries to discover the GPUs.  We've recently switched to using the Driver API as our primary source, and fall back to the cuda runtime library if that fails (most likely we'll remove the cuda runtime code in a few releases as long as the Driver API looks reliable)  Those libraries already implement filtering based on this environment variable, so the calls [here ](https://github.com/ollama/ollama/blob/main/gpu/gpu_info_nvcuda.c#L87) and [here ](https://github.com/ollama/ollama/blob/main/gpu/gpu_info_cudart.c#L85) will only return a subset of GPUs based on that variable if the user has set it.

In our scheduler, we pick which GPU (of the GPUs exposed) to run a model on, and when we run the subprocess for inference, we wire up the environment variable to ensure that subprocess uses exactly the set of GPUs we want it to use.

**Review by jmorganca — APPROVED** [review]
