### PR TITLE
Avoid rocm runner and dependency clash

### LINKED ISSUE #3035: AMD / ROCM failure on 0.1.29
# Config
**Environment**: Arch Linux; no docker
**GPU**: Radeon 6700xt
**Kernel**: 6.6.21-1-lts
**Env vars**: "HSA_OVERRIDE_GFX_VERSION=10.3.0" "OLLAMA_DEBUG=1"

# Summary

```
ollama run mistral

Error: write payload llama.cpp/build/linux/x86_64/rocm/lib/libext_server.so.gz: open /tmp/ollama93856906/rocm/libext_server.so: permission denied
```

```
## journalctl -b --unit ollama

Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.789-08:00 level=INFO source=images.go:806 msg="total blobs: 33"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.790-08:00 level=INFO source=images.go:813 msg="total unused blobs removed: 0"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
Mar 09 21:00:13 hwkiller-desktop ollama[98459]:  - using env:        export GIN_MODE=release
Mar 09 21:00:13 hwkiller-desktop ollama[98459]:  - using code:        gin.SetMode(gin.ReleaseMode)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/pull                 --> github.com/jmorganca/ollama/server.PullModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/generate             --> github.com/jmorganca/ollama/server.GenerateHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/chat                 --> github.com/jmorganca/ollama/server.ChatHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/embeddings           --> github.com/jmorganca/ollama/server.EmbeddingsHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/create               --> github.com/jmorganca/ollama/server.CreateModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/push                 --> github.com/jmorganca/ollama/server.PushModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/copy                 --> github.com/jmorganca/ollama/server.CopyModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] DELETE /api/delete               --> github.com/jmorganca/ollama/server.DeleteModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/show                 --> github.com/jmorganca/ollama/server.ShowModelHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /api/blobs/:digest        --> github.com/jmorganca/ollama/server.CreateBlobHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] HEAD   /api/blobs/:digest        --> github.com/jmorganca/ollama/server.HeadBlobHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] POST   /v1/chat/completions      --> github.com/jmorganca/ollama/server.ChatHandler (6 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] GET    /                         --> github.com/jmorganca/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] GET    /api/tags                 --> github.com/jmorganca/ollama/server.ListModelsHandler (5 handlers)
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: [GIN-debug] GET    /api/version              --> github.com/jmorganca/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)

Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.790-08:00 level=INFO source=routes.go:1082 msg="Listening on [::]:11434 (version 0.0.0)"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.790-08:00 level=INFO source=payload_common.go:112 msg="Extracting dynamic libraries to /tmp/ollama1019928670 ..."
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.889-08:00 level=INFO source=payload_common.go:139 msg="Dynamic LLM libraries [cpu rocm cpu_avx2 cpu_avx]"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.889-08:00 level=DEBUG source=payload_common.go:140 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.889-08:00 level=INFO source=gpu.go:77 msg="Detecting GPU type"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.889-08:00 level=INFO source=gpu.go:191 msg="Searching for GPU management library libnvidia-ml.so"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.889-08:00 level=DEBUG source=gpu.go:209 msg="gpu management search paths: [/usr/local/cuda/lib64/libnvidia-ml.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so* /usr/lib/x86_6>
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=INFO source=gpu.go:237 msg="Discovered GPU libraries: []"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=WARN source=amd_linux.go:50 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat >
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=INFO source=amd_linux.go:85 msg="detected amdgpu versions [gfx1031]"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /tmp/ollama1019928670/rocm"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /usr/share/ollama/lib/rocm"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /var/lib/ollama"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.894-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /opt/rocm/lib"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.896-08:00 level=DEBUG source=amd_linux.go:268 msg="host rocm linked /opt/rocm/lib => /tmp/ollama1019928670/rocm"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.896-08:00 level=DEBUG source=amd_linux.go:120 msg="skipping rocm gfx compatibility check with HSA_OVERRIDE_GFX_VERSION=10.3.0"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.897-08:00 level=DEBUG source=amd_linux.go:168 msg="discovering amdgpu devices [1]"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.897-08:00 level=INFO source=amd_linux.go:235 msg="[1] amdgpu totalMemory 12868124672"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.897-08:00 level=INFO source=amd_linux.go:236 msg="[1] amdgpu freeMemory  12868124672"
Mar 09 21:00:13 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:13.897-08:00 level=DEBUG source=gpu.go:180 msg="rocm detected 1 devices with 11044M available memory"

Mar 09 21:00:15 hwkiller-desktop ollama[98459]: [GIN] 2024/03/09 - 21:00:15 | 200 |       25.83µs |       127.0.0.1 | HEAD     "/"
Mar 09 21:00:15 hwkiller-desktop ollama[98459]: [GIN] 2024/03/09 - 21:00:15 | 200 |     299.559µs |       127.0.0.1 | POST     "/api/show"
Mar 09 21:00:15 hwkiller-desktop ollama[98459]: [GIN] 2024/03/09 - 21:00:15 | 200 |     163.959µs |       127.0.0.1 | POST     "/api/show"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=WARN source=amd_linux.go:50 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat >
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:85 msg="detected amdgpu versions [gfx1031]"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /tmp/ollama1019928670/rocm"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_linux.go:120 msg="skipping rocm gfx compatibility check with HSA_OVERRIDE_GFX_VERSION=10.3.0"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_linux.go:168 msg="discovering amdgpu devices [1]"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:235 msg="[1] amdgpu totalMemory 12868124672"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:236 msg="[1] amdgpu freeMemory  12868124672"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=gpu.go:180 msg="rocm detected 1 devices with 11044M available memory"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=WARN source=amd_linux.go:50 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers: amdgpu version file missing: /sys/module/amdgpu/version stat >
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:85 msg="detected amdgpu versions [gfx1031]"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_common.go:16 msg="evaluating potential rocm lib dir /tmp/ollama1019928670/rocm"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_linux.go:120 msg="skipping rocm gfx compatibility check with HSA_OVERRIDE_GFX_VERSION=10.3.0"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=DEBUG source=amd_linux.go:168 msg="discovering amdgpu devices [1]"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:235 msg="[1] amdgpu totalMemory 12868124672"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.156-08:00 level=INFO source=amd_linux.go:236 msg="[1] amdgpu freeMemory  12868124672"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.157-08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.157-08:00 level=DEBUG source=payload_common.go:93 msg="ordered list of LLM libraries to try [/tmp/ollama1019928670/rocm/libext_server.so /tmp/ollama1019928670/cpu_avx2/libext_server.so]"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.157-08:00 level=INFO source=llm.go:157 msg="/tmp/ollama1019928670/rocm/libext_server.so has disappeared, reloading libraries"
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: time=2024-03-09T21:00:16.157-08:00 level=INFO source=payload_common.go:112 msg="Extracting dynamic libraries to /tmp/ollama1019928670 ..."
Mar 09 21:00:16 hwkiller-desktop ollama[98459]: [GIN] 2024/03/09 - 21:00:16 | 500 |  237.588294ms |       127.0.0.1 | POST     "/api/chat"

```

# Notes

Interestingly, I had this exact same problem on 0.1.27, 0.1.28 also, and was what triggered me to look at this. Then v0.1.29 came out, and in the process of bisecting and cloning all new repos, v0.1.27/28 started working (I am legitimately confused about why, since I was getting a clean clone each time). 
I notice that my /tmp has several build objects; perhaps the builds were, at some point, using these [presumably wrong] objects?

image

```

### PR DESCRIPTION
**Pull request by dhiltgen**
Putting the rocm symlink next to the runners is risky.  This moves the payloads into a subdir to avoid potential clashes.

Fixes #3035 

Untested at the moment...

### CODE REVIEW

File: gpu/assets.go [hunk 1]
```diff
@@ -32,10 +32,11 @@ func Cleanup() {
 	lock.Lock()
 	defer lock.Unlock()
 	if payloadsDir != "" {
-		slog.Debug("cleaning up", "dir", payloadsDir)
-		err := os.RemoveAll(payloadsDir)
+		tmpDir := filepath.Clean(filepath.Join(payloadsDir, ".."))
```
Comment (BruceMacD) [inline gpu/assets.go:35]: What is above the payloads dir? Can we assume we have write access?

File: gpu/assets.go [hunk 2]
```diff
@@ -32,10 +32,11 @@ func Cleanup() {
...
+		slog.Debug("cleaning up", "dir", tmpDir)
+		err := os.RemoveAll(tmpDir)
```
Comment (BruceMacD) [inline gpu/assets.go:37]: This looks like it will remove the directory above the payloads dir? Feels really risky where it is opaque what that is

**Review by jmorganca — APPROVED** [review]

File: gpu/assets.go (hunk 1 above)
Comment (dhiltgen) [reply gpu/assets.go:35]: I'll add some comments to help clarify what's going on.  Line 26 adds a new sub directory above the tmpDir so that we can disambiguate between rocm runner and the rocm sym link.
