### PR TITLE
fix(mllama): sync backend between batches

### LINKED ISSUE #7558: llama3.2-vision crash on multiple cuda GPUs - unspecified launch failure
### What is the issue?

Running on 3.2-vision:11b works with text and images
Running on 3.2-vision:90b works with text, segfault on images
Running llava: works with text and images

Debug log from segfault with text and image:
mllama_model_load: description:  vision encoder for Mllama
mllama_model_load: GGUF version: 3
mllama_model_load: alignment:    32
mllama_model_load: n_tensors:    512
mllama_model_load: n_kv:         17
mllama_model_load: ftype:        f16
mllama_model_load:
mllama_model_load: vision using CUDA backend
time=2024-11-07T04:46:42.696Z level=DEBUG source=server.go:615 msg="model load completed, waiting for server to become available" status="llm server loading model"
mllama_model_load: compute allocated memory: 2853.34 MB
time=2024-11-07T04:46:43.199Z level=INFO source=server.go:606 msg="llama runner started in 23.62 seconds"
time=2024-11-07T04:46:43.199Z level=DEBUG source=sched.go:462 msg="finished setting up runner" model=/home/user/.ollama/models/blobs/sha256-da63a910e34997d50c9f21cc7f16996d1e76e1c128b13319edd68348f760ecc7
time=2024-11-07T04:46:43.452Z level=DEBUG source=routes.go:1457 msg="chat request" images=1 prompt="<|start_header_id|>user<|end_header_id|>\n\n[img-0]<|image|>this is a random frame. describe in detail everything you can interpret. Ideally keep your response concise and information dense since this will be read in a chat room. ANYTHING OVER 200 CHARACTERS WILL BE CUT OFF.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
time=2024-11-07T04:46:46.139Z level=DEBUG source=image.go:175 msg="storing image embeddings in cache" entry=0 used=0001-01-01T00:00:00.000Z
time=2024-11-07T04:46:46.139Z level=DEBUG source=cache.go:99 msg="loading cache slot" id=0 cache=0 prompt=61 used=0 remaining=61
CUDA error: unspecified launch failure
  current device: 3, in function ggml_backend_cuda_synchronize at ggml-cuda.cu:2508
  cudaStreamSynchronize(cuda_ctx->stream())
ggml-cuda.cu:132: CUDA error
SIGSEGV: segmentation violation
PC=0x72e7ad3ecc57 m=7 sigcode=1 addr=0x213203fcc
signal arrived during cgo execution

goroutine 7 gp=0xc00029c000 m=7 mp=0xc000302008 [syscall]:
runtime.cgocall(0x60e54306eeb0, 0xc000185b60)
        runtime/cgocall.go:157 +0x4b fp=0xc000185b38 sp=0xc000185b00 pc=0x60e542df13cb
github.com/ollama/ollama/llama._Cfunc_llama_decode(0x72e7180064a0, {0x37, 0x72e7183ae990, 0x0, 0x0, 0x72e7183af1a0, 0x72e7183af9b0, 0x72e7183b01c0, 0x72d1281ef3e0, 0x0, ...})
        _cgo_gotypes.go:543 +0x52 fp=0xc000185b60 sp=0xc000185b38 pc=0x60e542eee952
github.com/ollama/ollama/llama.(*Context).Decode.func1(0x60e54306aceb?, 0x72e7180064a0?)
        github.com/ollama/ollama/llama/llama.go:167 +0xd8 fp=0xc000185c80 sp=0xc000185b60 pc=0x60e542ef0e78
github.com/ollama/ollama/llama.(*Context).Decode(0xc0001ec140?, 0x1?)
        github.com/ollama/ollama/llama/llama.go:167 +0x17 fp=0xc000185cc8 sp=0xc000185c80 pc=0x60e542ef0cd7
main.(*Server).processBatch(0xc0001d0120, 0xc000234000, 0xc000234070)
        github.com/ollama/ollama/llama/runner/runner.go:424 +0x29e fp=0xc000185ed0 sp=0xc000185cc8 pc=0x60e543069d1e
main.(*Server).run(0xc0001d0120, {0x60e5433a8a40, 0xc0001a60a0})
        github.com/ollama/ollama/llama/runner/runner.go:338 +0x1a5 fp=0xc000185fb8 sp=0xc000185ed0 pc=0x60e543069705
main.main.gowrap2()
        github.com/ollama/ollama/llama/runner/runner.go:907 +0x28 fp=0xc000185fe0 sp=0xc000185fb8 pc=0x60e54306dee8
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000185fe8 sp=0xc000185fe0 pc=0x60e542e59de1
created by main.main in goroutine 1
        github.com/ollama/ollama/llama/runner/runner.go:907 +0xcab

goroutine 1 gp=0xc0000061c0 m=nil [IO wait]:
runtime.gopark(0xc000034008?, 0x0?, 0xc0?, 0x61?, 0xc00002d8c0?)
        runtime/proc.go:402 +0xce fp=0xc0001f5888 sp=0xc0001f5868 pc=0x60e542e2800e
runtime.netpollblock(0xc00002d920?, 0x42df0b26?, 0xe5?)
                                                                                

### OS

_No response_

### GPU

Nvidia

### CPU

_No response_

### Ollama version

0.4

### PR DESCRIPTION
**Pull request by mxyng**
On multi-GPUs and cross attention specifically, sync the backend between batches to ensure operations are complete before moving on 

Resolves #7558

### CODE REVIEW

File: llama/runner/runner.go [hunk 1]
```diff
@@ -427,6 +427,10 @@ func (s *Server) processBatch(tokenBatch *llama.Batch, embedBatch *llama.Batch)
 		return
 	}
 
+	if crossAttention {
+		s.lc.Synchronize()
+	}
```
Comment (jessegross) [inline llama/runner/runner.go:432]: Can you add a comment explaining why this is necessary?

**Review by jessegross — APPROVED** [review]
